### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by jgrzebyta** [VisualDataWeb/WebVOWL#100]
In my other project I will set up a WebVOWL service to visualize my repository. For that I will create a Dockerfile. If you like I might share the file in PR. If so where in the files tree I might add that? What about `/doc` folder?

**Comment by steffen-l** [comment]
Sounds good to me. We also use Docker in case of [VoCol](https://github.com/vocol/vocol), which includes WebVOWL. Of course, you need to package [OWL2VOWL](https://github.com/VisualDataWeb/OWL2VOWL) as well if you want to allow for the rendering of custom ontologies.

**Comment by jgrzebyta** [comment]
So I will prepare initial PR for that today.
