### ISSUE TITLE
How to load json file

### ISSUE THREAD

**Issue by rickywu** [VisualDataWeb/WebVOWL#101]
I already download the source and use npm install and build successfully but if I open the index.html file, it shows
`Ontology could not be loaded.
Is it a valid OWL ontology? Please check with OWL Validator.`

Seems it can't find the data json file, did I missed any thing?

I checked Chrome console and find this error
`XMLHttpRequest cannot load file:///E:/Workstation/WebVOWL/deploy/data/foaf.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`

Seems not support file method, how should I use my own url?

**Comment by steffen-l** [comment]
I assume you use Google Chrome as a browser. Note the error message indicating the CORS issue. You can use Firefox instead (as less CORS restrictive) or go for another solution (upload the files to some server, changing the configuration of Chrome, using a proxy, etc.). Hope this helps.

**Comment by rickywu** [comment]
Understand, seems I also can change source to read from another source.
