### ISSUE TITLE
Visualize an Ontology using timeline

### ISSUE THREAD

**Issue by AbhijeetThakur** [VisualDataWeb/WebVOWL#103]
Hi,

Is there are any ways to update / visualize an Ontology  graph with respect to timeline. Timeline is  the  slider with series of time events. What I'm trying to achieve is, change the graph on the movement of slider.

Thanks in advance.

Regards,
Abhijeet

**Comment by steffen-l** [comment]
That's, of course, possible - but not a feature of WebVOWL. For instance, the feature could work similar to the "degree of collapsing" slider in the "Filter" menu, but with different ontology versions. Another option would be to use small multiples, as we suggested in: http://ceur-ws.org/Vol-1456/paper7.pdf There are different ways to realize - the design decision and technical realization is up to you ;-)
