### ISSUE TITLE
How to apply in angular

### ISSUE THREAD

**Issue by rickywu** [VisualDataWeb/WebVOWL#104]
I want to call WebVOWL to initialize in Angular app, but got error.
How can I use WebVOWL as module in Angular?

Anyone has suggestion?

**Comment by rickywu** [comment]
I use embedded page to apply WebVOWL in angular application.

**Comment by AbhijeetThakur** [comment]
@rickywu  Can you please share code snippet,  to apply WebVOWL in angular application?
I'm also want to use WebVOWL as module in Angular.

Thanks in advanced !!!

**Comment by steffen-l** [comment]
Duplicate of issue #108

**Comment by steffen-l** [comment]
Duplicate of issue #108

**Comment by rickywu** [comment]
@AbhijeetThakur  @steffen-l 
please follow this:
insert iframe in angular html page:

> <div class="noword">No data</div>
> <iframe id="productIfream" runat="server" src="../../../assets/webVOWL/index.html" frameborder="no" border="0" marginwidth="0"
>     marginheight="0" scrolling="no" allowtransparency="yes"></iframe>

in ts file:

> import * as d3 from "d3";
> 
> call process when init iframe:
> 	ngOnInit() {
> 		this.oninitIfream();
> 		//$(".waiting").show();
> 		//this.addd3();
> 		this.postsession();
> 	}

> 	postsession(){
> 	  sessionStorage.setItem('pathurl', this.url+'/app/getWebvowlData?code=1&class=system');
> 	 //这里的pathurl存入缓存，webVOWL.js里引用
> 	}


postsession will fetch data and transfer data to the index.html when init iframe, the js in index.html will call WebVOWL

**Comment by steffen-l** [comment]
Thanks for sharing, @rickywu!

**Comment by prasad4fun** [comment]
I have answered above question here.

https://stackoverflow.com/questions/51523444/how-to-reuse-existing-vanilla-js-d3-visualization-with-angular-5
