### ISSUE TITLE
local classes are not being displayed when ontology has imports

### ISSUE THREAD

**Issue by kartgk** [VisualDataWeb/WebVOWL#105]
When using the below ontology, the visualization shows only the imported classes. The classes defined in this ontology are not displayed ( BranchOfGovernment, GovernmentBody ...).  But when the imports are removed, all the classes are displayed correctly.

[GovernmentEntities_txt.txt](https://github.com/VisualDataWeb/WebVOWL/files/1486657/GovernmentEntities_txt.txt)

**Comment by kartgk** [comment]
Can someone take a look at this. This is a Blocker for us. We are planning to go live by Dec 30.

**Comment by vitalis-wiens** [comment]
For me it works

1) You can search for 'government body' in the search bar, and using the locate button (next to the search bar) it will translate the viewport to its position
2) BranchOfGovernment: it is filtered out when loading the ontology 
There is a 'Filter' menu where you can set the degree of collapsing 
or you can use this link which will show you the full ontology without any filters:

http://visualdataweb.de/webvowl/#opts=[doc=0;filter_disjoint=false;]#iri=https://github.com/VisualDataWeb/WebVOWL/files/1486657/GovernmentEntities_txt.txt

**Comment by kartgk** [comment]
Cool, thanks. Yes changing the degree of collapsing shows all the classes. Kind of feels non intuitive from a usability view that you have to bring the collapsing level to 0 to see all the local classes, this actually floods the UI with all the imported classes. But the locate button is greatly helpful.

**Comment by vitalis-wiens** [comment]
Usability is the key word here, ever tried to do this on a smart phone? 
That`s why we have a default detection which in order to reduce the number of nodes< 50 on loading
And the filter button blinks when it is > 0 on a load

**Comment by kartgk** [comment]
That definitely makes sense, didnt think about from a smart phone or any other screen perspective. Just in this case, what i felt or the feedback i m getting is, i should be seeing my local classes first and do any tweaking only if i wanted to see the imported classes. Could that be a filter ?
