### ISSUE TITLE
Visualization not generated for owl:intersectionOf

### ISSUE THREAD

**Issue by kartgk** [VisualDataWeb/WebVOWL#106]
Consider the below ontology, webvowl is not generating visualization for the owl:intersectionOf constructs. Check the class FederalGovernment.

[GovernmentEntities.txt](https://github.com/VisualDataWeb/WebVOWL/files/1486669/GovernmentEntities.txt)

**Comment by steffen-l** [comment]
Thanks for sharing. The construction you are pointing to is indeed not yet properly supported by the current OWL2VOWL converter.

**Comment by steffen-l** [comment]
I move the issue to the OWL2VOWL repo (https://github.com/VisualDataWeb/OWL2VOWL/issues/42) and  close it here.
