### ISSUE TITLE
SKOS Ontology Already exists Error when loading ontology

### ISSUE THREAD

**Issue by kartgk** [VisualDataWeb/WebVOWL#107]
When loading ontology , getting this error. Please advise.

[CorporationEquity.txt](https://github.com/VisualDataWeb/WebVOWL/files/1487241/CorporationEquity.txt)

{"timestamp":1511173076657,"status":500,"error":"Internal Server Error","exception":"java.lang.IllegalStateException","message":"org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <https://www.w3.org/2004/02/skos/core> Cause: Ontology already exists. OntologyID(OntologyIRI(<http://www.w3.org/2004/02/skos/core>) VersionIRI(<null>))","path":"/webvowl_1.0.6/convert"}

**Comment by kartgk** [comment]
Can someone take a look at this. This is a Blocker for us. We are planning to go live by Dec 30.

**Comment by vitalis-wiens** [comment]
This is an OWL2VOWL issue, sofar I could identify that the imported ontology defines also skos/core (e.g CorporateBodies) and this leads then to the Ontology already exist error

**Comment by vitalis-wiens** [comment]
A new version of WebVOWL and OWL2VOWL  is now release, it provides now more loading information and error details.

With the new version you will see that the ontology is unfortunately not correct 

* lineNumber: 47; columnNumber: 34; The prefix "skos" for element "skos:definition" is not bound. 

Best Regards, 
Vitalis
