### ISSUE TITLE
How to convert the WebVOWL into angular 4 as a component?

### ISSUE THREAD

**Issue by AbhijeetThakur** [VisualDataWeb/WebVOWL#108]
Hello,
I'm using WebVOWL in my project. It's a very good application. 
Now I'm trying to convert it into the angular 4 component.  Can please any one please help / guide me to convert this.

Thanks in advance !!!

**Comment by steffen-l** [comment]
Hi @AbhijeetThakur, I am afraid but this is beyond the support that the WebVOWL developers could provide here. However, we welcome everyone sharing their costumizations or forking the project - so if you realize an angular version of WebVOWL, please be so kind and share it here.

A related issue already exists (issue #104), but we closed it some time ago, as there doesn't seem to be anybody taking care of it.

Kindly find an example of an embedded WebVOWL visualization without any surrounding GUI in the VOWL 2 spec: http://vowl.visualdataweb.org/v2/#example

**Comment by AbhijeetThakur** [comment]
Thanks @steffen-l.

**Comment by prasad4fun** [comment]
Hi i have answered above question here.

https://stackoverflow.com/questions/51523444/how-to-reuse-existing-vanilla-js-d3-visualization-with-angular-5
