### ISSUE TITLE
Cannot Draw to much instances

### ISSUE THREAD

**Issue by joaosalvado10** [VisualDataWeb/WebVOWL#109]
Hello, when I upload my json file on http://visualdataweb.de/webvowl/.
Only the bubbles that have connection are drawn here is my json file.

[json_file.txt](https://github.com/VisualDataWeb/WebVOWL/files/1551471/json_file.txt)

**Comment by steffen-l** [comment]
Not sure if I got you right, but have you tried the "degree of collapsing" slider in the filter menu?

**Comment by joaosalvado10** [comment]
Solved by calling the 'redraw' 2 times  on html file. Still after doing it , the filter buttom and the others are hidden on the right.

**Comment by steffen-l** [comment]
Glad to hear you solved the problem. However, it is hard to understand your issue without a more precise description or screenshot sharing. What do your mean by "redraw"? The "reset" button? What do you mean with "hidden on the right"? On what device, screen resolution, browser size?
