### ISSUE TITLE
Create new class/property

### ISSUE THREAD

**Issue by ajrmoreira** [VisualDataWeb/WebVOWL#113]
Hello, 
I was wondering if it is possible to create a new class and/or a new Property.
In my case, I have a broader color code than the one available by default, so I need new propertyAttributtes.

I've tried to add elements in the .css file, such as ".my_property { fill: #colorcode}", but it doesn't work.
I've looked for functions in the .js files that define the color code of the classes/properties, copied and pasted the code changing the name to ".my_property", but that didn't work as well. 

Are there any other files where I need to add the ".my_property"?

Many thanks!

**Comment by steffen-l** [comment]
Hi @ajrmoreira, have you found the "multicolor" toggle in the "modes" menu? Every class/property having a different base URI gets assigned an individual background color (note that the total number of colors humans can clearly distinguish is limited though).

Apart from that, note that VOWL is a notation particularly for the language constructs of the OWL Web Ontology Language. If you want to extend the notation for your own domain-specific language or alike, you have to change the JavaScript and CSS code at several locations accordingly - which is possible but requires some basic understanding of the JS code.

**Comment by ajrmoreira** [comment]
Thank you @steffen-l 
I'm having another issue...I'm loading a .json with 68 classes, and 420 properties, but when I plot, it doens't show all the classes, do you have any idea why this is happening?

many thanks

**Comment by steffen-l** [comment]
Note that a "degree of collapsing" value is automatically set in many cases to prevent a cluttered graph, performance issues, etc. You can set it to zero via the slider in the filter menu to see the full ontology graph.

**Comment by ajrmoreira** [comment]
Oh! That's so simple and so nice!
Thank your for the explanation. =)

**Comment by ajrmoreira** [comment]
Hello @steffen-l 
I'm sorry to "re-open" this topic, I'm having some issues finding all JS and CSS code I need to change in order to add / change color codes.
More specifically, I need a wider variety of "Property", do you have some kind of mapping of where I need add code?

Thanks
