### ISSUE TITLE
New object property

### ISSUE THREAD

**Issue by ajrmoreira** [VisualDataWeb/WebVOWL#116]
Hello everyone,

How can I create a new object property?
I need a broader set of color codes for the property attributes.

Thanks in advance,
Moreira

**Comment by vitalis-wiens** [comment]
Hi,
You could create them inside src/webvowl/js/elements/properties/implementation

Take a look how these are implemented( they use a BasePropererty as a superClass, and just set some attributes and styles )

I really depends on what you want to build

 and if you want to make a quick hack
 you could manually set the style of the property or directly its backgroundColor
