### ISSUE TITLE
when is the next release, eager to use the Zoom slider features

### ISSUE THREAD

**Issue by akaur13** [VisualDataWeb/WebVOWL#120]
Hi ,
I am simply in love with WEBVOWL lib keep up the good work. would you have any dates for zoom slider release? Keen on using that in my app for magnifying feature.

Regards
AK

**Comment by steffen-l** [comment]
We just released it to the public today ;-) Check out http://vowl.visualdataweb.org/webvowl.html There, you can also find a link to a WebVOWL version with the new - still experimental - editing features of WebVOWL (WebVOWL Editor).

**Comment by christopheralcock** [comment]
Congratulations Steffen, this release is fantastic. Performance improvements on large ontologies really noticeable and the editor is a great idea. Thanks for all the great work to you and the team!

**Comment by steffen-l** [comment]
Thanks, Christopher, much appreciated! Kudos goes to Vitalis in particular who did a great job in implementing the new editing functionality.
