### ISSUE TITLE
SVG export doesn't work anymore

### ISSUE THREAD

**Issue by giorgiobevilacqua** [VisualDataWeb/WebVOWL#121]
Hi,
I usually use WebVOWL to create a visual version of the ontology using the pick&pin mode and then exporting the SVG image.
But now, if I try to export an SVG, the page refreshes and the export doesn't work. I tried to do it  both with Firefox and Chromium. 
Is there a way to fix it?
Thank you for your work, all the best,
Giorgio

**Comment by vitalis-wiens** [comment]
Hi, thanks for reporting this issue,

I will investigate it, and fix it as soon as possible.

Additionally  we will release soon the next version of WebVOWL ( 1.1.1 ) .

Vitalis

**Comment by vitalis-wiens** [comment]
Hi, 

I just want to let you know that the SVG exporter  issue is now fixed here in GitHub
( but not at yet at http://visualdataweb.de/webvowl/  ) 

Soon we will also update the visualdataweb.de version 

when this is done I will close this issue 

Thanks again for reporting it ! 

Best  regards , 
Vitalis

**Comment by vitalis-wiens** [comment]
New version of WebVOWL (1.1.1) is released

**Comment by giorgiobevilacqua** [comment]
I tried the new release and the SVG export works fine!

Thank you so much,
Giorgio

**Comment by steffen-l** [comment]
We are glad to hear that. The latest WebVOWL version (version 1.1.1) should work very stable. If you find any more issues, please do not hesitate to report here. Much appreciated!

**Comment by vitalis-wiens** [comment]
Hi, I used Firefox or Chrome for exporting the svg and Incscape to view it.

Alternatively, you could try out the tex export, which will generate a tex file that renders the graph as tkiz.
You then can simply import this file and create a pdf out of it.

The comments in the generated file describe how to create a the pdf and include the input as a figure:

%%%%%%%%%%%%%%% Example Parent Document %%%%%%%%%%%%%%%%%%%%%%%
\documentclass{article} 
\usepackage{tikz} 
\usepackage{helvet} 
\usetikzlibrary{decorations.markings,decorations.shapes,decorations,arrows,automata,backgrounds,petri,shapes.geometric} 
\usepackage{xcolor} 

\begin{document} 
\section{Example} 
  This is an example. 
  \begin{figure} 
    \input{<THIS_FILE_NAME>} % << tex file name for the graph 
    \caption{A generated graph with TKIZ using alpha version of the TeX exporter of WebVOWL (version 1.1.3) } 
  \end{figure} 
\end{document} 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

I hope this helps.
