### ISSUE TITLE
[other] webvowl online not working

### ISSUE THREAD

**Issue by r0xen** [VisualDataWeb/WebVOWL#131]
Hello, probably this isn't the best place, but seems like the online version doesn't work. It gives 503 http://www.visualdataweb.de/webvowl/ are you doing some kinda of updates or what?

I loved the service, it was really handy.

**Comment by steffen-l** [comment]
Thanks for the nice words and for letting us know. The public WebVOWL version is back online and running again: http://www.visualdataweb.de/webvowl/
