### ISSUE TITLE
How Can I Pass Data To WebVOWL from jsontext

### ISSUE THREAD

**Issue by kadirkalkan** [VisualDataWeb/WebVOWL#132]
Hi, i have a json text and i want to send this to webvowl but i couldn't find any way for this. How can i do this feeding from javascript.

**Comment by kadirkalkan** [comment]
Thanks for answer but i wonder how can i pass a prepared json data to vebowl in javascript;
i figure out this with write a event listener for a hidden button on page inside ontologyMenu.js file and i get json text from webservice with xhr and send this text as parameter to loadOntologyFromText() method.
i changed source code but i wonder how can i reach this method(loadOntologyFromText()) out of javascript file from client side <script> block

My External Listener Function = 

`d3.select("#opnextButton").on("click", function () {
        displayLoadingIndicators();
        var scenarioID = document.getElementById("opnextTaskId").value;
        var getRdf = new XMLHttpRequest();
        getRdf.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
                var rdfObject = {value : "json"}
                rdfObject.value = JSON.parse(getRdf.responseText).value;
                console.log(rdfObject);
                var getJsonFromRdf = new XMLHttpRequest();
                getJsonFromRdf.onreadystatechange = function() {
                    if (this.readyState == 4 && this.status == 200) {
                        console.log("JSON : ",JSON.parse(getJsonFromRdf.responseText).message);
                        loadOntologyFromText(JSON.parse(getJsonFromRdf.responseText).message,"opnext","opnext");
                    	hideLoadingInformations();
                    }
                };
                getJsonFromRdf.open("POST", "http://opnextappstatuscontroller.pragmalinq.com/appstatuscontroller/rdftojson", true);
                getJsonFromRdf.setRequestHeader("Content-Type", "application/json");
                getJsonFromRdf.send(JSON.stringify(rdfObject));
            }
        };
        getRdf.open("POST", "http://localhost:8080/OPNextWS_war/opnext/planner/getOWLRDF", true);
        getRdf.setRequestHeader("Content-Type", "application/json");
        getRdf.send(scenarioID);
    })`

**Comment by vitalis-wiens** [comment]
Hi, not exactly sure but if you want to reach this function somewhere from the client side
you can use the graph.options().ontologyMenu().<function_in_ontologyMenu>

but you might also want to take a look at the function  *loadOntologyFromText* in *app.js*
this function gets the content of the json file as a parameter  and "forwards" it to the graph.

I hope this helps
