### ISSUE TITLE
"Ontology could not be loaded" issue in webvowl

### ISSUE THREAD

**Issue by marwa811** [VisualDataWeb/WebVOWL#134]
Hello,
Actually, webvwol is really great work.. I need to use it in visualizing ontologies in my application (which is on ontology selection) .. I am not so good in JavaScript and I don't know from where to start.
What I did till now: 
1. I used owl2vowl  java library to convert an ontology to JSON format.
2. then, I cloned your project webvwol from github to a new project just to see how it is working, but unfortunately, it doesn't work . only the interface but no functionalities!! 

Regards,
Marwa

**Comment by vitalis-wiens** [comment]
Hi, did you complied WebVOWL with npm install? 
then there is a folder called "deploy" there is an index.html file, when you open this one 
it should work 

Kind Regards, 
Vitalis

**Comment by marwa811** [comment]
After some investigations, I discovered that the problem is from Chrome, as when I open index.html in Firefox it works perfectly.  
Do you know how to fix the issue with Chrome?? is it a security issue??

Regards,
Marwa

**Comment by vitalis-wiens** [comment]
Hi, yes you are right, when using the local version Chrome does not allow you to access files
"Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https."

There is an add-on for chrome allowing you to use CORS 
I used this one : Access-Control-Allow-Origin:* 

In the next version we will add a module to allow to paste text (JSON /  OWL)  which will allow you to handle this kind of situations 

Kind Regards, 
Vitalis

**Comment by marwa811** [comment]
OK, Thanks a lot :)
