### ISSUE TITLE
WEBVOwl JSON Format to Owl ontology serialization

### ISSUE THREAD

**Issue by SpyrosKou** [VisualDataWeb/WebVOWL#135]
Hi,

The current version of WebVOWL support the following scenario:
1.Importing an OWL file.
2.Modifying the visualization.
3.Exporting the visualization in JSON format.
4.Opening a new WebVOWL window, importing the JSON Format from step 3.

However it is not possible to export from step 4 a serialization of the ontology in e.g. owl/rdf-xml format. 

I was wondering if it is possible to export the ontology owl file from the JSON format produced by WebVOWL. Of course the visualization information will be lost. 
However if the JSON format keeps all the information included in an owl file, it should be in principle possible to extract the ontology.

I would like to ask if this is possible.

Thank you

**Comment by vitalis-wiens** [comment]
Hi, 

in  general it is possible, we have already implemented it in the beta of the WebVOWL Editor : http://visualdataweb.de/webvowl_editor/

It allows you to load/edit or create a new ontology.

The "Export" has the option "Export as TTL" 
Note: This is still in development and does not yet support all OWL constructs

Kind Regards, 

Vitalis

**Comment by SpyrosKou** [comment]
Thank you for your answer!
