### ISSUE TITLE
Cannot visualize Ontology - Empty Graph

### ISSUE THREAD

**Issue by kartgk** [VisualDataWeb/WebVOWL#138]
Trying to visualize our ontology

https://spec.edmcouncil.org/fibo/ontology/master/latest/BE/Corporations/Corporations/

The screen shows these error messages

Retrieving ontology from IRI: https://spec.edmcouncil.org/fibo/ontology/master/latest/BE/Corporations/Corporations/
Parsing ontology with OWL API ....... done 
Generating ontology graph ... done

Reading ontology graph ... failed
Error: Received empty graph
Failed to load ontology

Not able to figure what the error is. But actually downloading the file and visualization works.

**Comment by vitalis-wiens** [comment]
Hi,

I`ve tested it and it works without any issues for both Firefox and Chrome 
http://www.visualdataweb.de/webvowl/#iri=https://spec.edmcouncil.org/fibo/ontology/master/latest/BE/Corporations/Corporations/

**Comment by kartgk** [comment]
Thanks. Seems to be my company proxy. It also works for me outside the network.
