### ISSUE TITLE
Wrong display of models with data properties

### ISSUE THREAD

**Issue by miraks31** [VisualDataWeb/WebVOWL#142]
Hi,

With WEBVOWL 1.1.2, if I upload a model with data properties (CM Model Business Level 1.5.owl) the display is incorrect. if I upload the same model without data properties (CM Model Business Level 1.5 without data properties.owl) the display is correct. 

[CM Model Business Level 1.5.zip](https://github.com/VisualDataWeb/WebVOWL/files/2642841/CM.Model.Business.Level.1.5.zip)

**Expected result**: The display should be correction with or without data properties.

**Comment by miraks31** [comment]
Hi,

With WEBVOWL 1.1.2, if I upload a model with data properties (CM Model Business Level 1.5.owl) the display is incorrect. if I upload the same model without data properties (CM Model Business Level 1.5 without data properties.owl) the display is correct. 

[CM Model Business Level 1.5.zip](https://github.com/VisualDataWeb/WebVOWL/files/2642841/CM.Model.Business.Level.1.5.zip)

**Expected result**: The display should be correction with or without data properties.

**Comment by vitalis-wiens** [comment]
The issue has been fixed with the newest version 1.1.4 of WebVOWL
(including an update in OWL2VOWL) .

Restrictions on DatatypeProperties like the following : 
 <DataPropertyDomain>
        <DataProperty IRI="#OWLDataProperty_6ccd0f09_231c_4025_b606_e6bf53d54ced"/>
        <ObjectSomeValuesFrom>
            <ObjectProperty IRI="#OWLObjectProperty_727e8c3d_7f55_4b62_ac8b_bcdeffcdb3a8"/>
            <Class IRI="#Applicability"/>
        </ObjectSomeValuesFrom>
    </DataPropertyDomain>

are yet not supported by OWL2VOWL 

Kind Regards, 
Vitalis
