### ISSUE TITLE
Inconsistent whitespace usage throughout project

### ISSUE THREAD

**Issue by hidde-jan** [VisualDataWeb/WebVOWL#150]
A quick glance at different files (both html, css and js) shows that currently whitespace is used inconsistently throughout the whole repository. While whitespace is predominantly using tabs, at a few places spaces are used. From this, it seems that a tab width of 4 spaces is used. On GitHub (and other places) tab width is often set to 8 spaces, causing problems when reading the source online.

Tab usage has been superseded by space usage for whitespace in a lot of languages with the indent width set to a specific number of spaces (2 for javascript for instance).

**Comment by vitalis-wiens** [comment]
Hi, 
thanks for the hint.
Set code-style to be now for tab=2 spaces 
It will be fixed with the next commit  (soon) 

Vitalis :)

**Comment by vitalis-wiens** [comment]
Done :)
