### ISSUE TITLE
Uncaught DOMException when loading stand-alone WebVOWL

### ISSUE THREAD

**Issue by jandekj** [VisualDataWeb/WebVOWL#151]
An exception is thrown when starting WebVOWL stand-alone 1.1.4 in Chrome:
`webvowl.app.js:5 Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at n (.../WebVOWL/js/webvowl.app.js:5:12205)
    at e.exports (.../WebVOWL/js/webvowl.app.js:5:12404)
    at Object.e.exports [as app] (.../WebVOWL/js/webvowl.app.js:1:7647)
    at .../WebVOWL/index.html:473:33`

Using the stand-alone version from http://downloads.visualdataweb.de/webvowl_1.1.4.zip
Browser: Chrome Version 73.0.3683.103 (Official Build) (64-bit).
FYI, it starts fine in Edge.

**Comment by vitalis-wiens** [comment]
Thanks! 
I have found the issue: chrome, does not allow to load files directly ( CORS issue when loading standalone in local environment)
I  have fixed it and it will be added soon, currently working on an other feature :) 

Kind regards, Vitalis

**Comment by vitalis-wiens** [comment]
Updated the version on GitHub :)
The stand-alone version will be provided soon at visualdataweb.de

Kind regards, Vitalis
