### ISSUE TITLE
Error when loading stand-alone WebVOWL

### ISSUE THREAD

**Issue by dbarj** [VisualDataWeb/WebVOWL#159]
The error at #151 and #153 are back. I've tested webvowl_1.1.4.zip and webvowl_1.1.5.zip (from github release and also compiling it) and I can't load the index pages on both Firefox and Chrome running in MacOS:
- Firefox - 68.0.1 (64-bit)
- Chrome - Version 75.0.3770.142 (Official Build) (64-bit)

However, it is loading on Chrome when CORS is disabled and in Firefox changing security.fileuri.strict_origin_policy to false.

Errors are:

Firefox:
`SecurityError: The operation is insecure. webvowl.app.js:8926
    findCSS_Index file:///Users/rodrigo.jorge/Desktop/oci360/WebVOWL-1.1.5/deploy/js/webvowl.app.js:8926
    exports file:///Users/rodrigo.jorge/Desktop/oci360/WebVOWL-1.1.5/deploy/js/webvowl.app.js:8946
    exports file:///Users/rodrigo.jorge/Desktop/oci360/WebVOWL-1.1.5/deploy/js/webvowl.app.js:542
    <anonymous> file:///Users/rodrigo.jorge/Desktop/oci360/WebVOWL-1.1.5/deploy/index.html:507`

Chrome:
`Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at findCSS_Index (file:///Users/rodrigo.jorge/Desktop/oci360/WebVOWL-1.1.5/deploy/js/webvowl.app.js:8926:57)
    at webvowl.app.343.module.exports (file:///Users/rodrigo.jorge/Desktop/oci360/WebVOWL-1.1.5/deploy/js/webvowl.app.js:8946:4)
    at Object.webvowl.app.322.module.exports [as app] (file:///Users/rodrigo.jorge/Desktop/oci360/WebVOWL-1.1.5/deploy/js/webvowl.app.js:542:46)
    at file:///Users/rodrigo.jorge/Desktop/oci360/WebVOWL-1.1.5/deploy/index.html:507:33`

**Comment by vitalis-wiens** [comment]
Hi thanks for the notification! 

I checked my Firefox version and the security settings 
(Using Linux Mint, Firefox 68.0.1 (64bit) and having the security.fileuri.strict_origin_policy = true ) 

Mysteriously it is working, 

I will try to find an other way to handle the warning messages. 

Cheers
Vitalis

**Comment by dgarijo** [comment]
Any updates on this issue? I am currently unable to view any of the visualizations I create :(
Errors on Chrome and Firefox are the same as above

**Comment by vitalis-wiens** [comment]
Just updated the code, and tested it with the newest Firefox and chrome versions 

@dgarijo  let me know if there is anything else you need 
(Auto-loading the json files will not work out of the box, since CORS) 
but you can now drag and drop files into the viewport of the graph area. 

Cheers Vitalis
