### ISSUE TITLE
cardinality of min 0, max 1 is represented in WebVOWL as *..1 instead of 0..1 as documented

### ISSUE THREAD

**Issue by eric-jahn** [VisualDataWeb/WebVOWL#177]
I have the following stanzas:

```
###  http://www.hudhdx.info/Resources/Vendors/FY2022/owl#Client
hmisowl:Client rdf:type owl:Class ;
               rdfs:subClassOf [ rdf:type owl:Restriction ;
                                 owl:onProperty hmisowl:hasClientVeteranInfo ;
                                 owl:minCardinality "0"^^xsd:nonNegativeInteger
                               ] ,
                               [ rdf:type owl:Restriction ;
                                 owl:onProperty hmisowl:hasClientVeteranInfo ;
                                 owl:maxCardinality "1"^^xsd:nonNegativeInteger
                               ] .
###  http://www.hudhdx.info/Resources/Vendors/FY2022/owl#hasClientVeteranInfo
hmisowl:hasClientVeteranInfo rdf:type owl:ObjectProperty ;
                             rdfs:domain hmisowl:Client ;
                             rdfs:range hmisowl:ClientVeteranInfo .
```
but it renders *..1:

![cvi](https://user-images.githubusercontent.com/4115079/121202162-1247ee00-c843-11eb-8ada-8388b1e5625d.png)

If I change the values to, say "5..15", or "3..12", then it it fine, but the "0" in "0..1" itself is being replaced by "*".

**Comment by gitongithub** [comment]
I would like to work on this issue. I believe when only maxCardinality is defined (and minCardinality isn't specified), we should set the minimum cardinality as 0 and reflect the same in [generateCardinalityText()](https://github.com/VisualDataWeb/WebVOWL/blob/d48fdf663107426023762c7178f2ebc00e5e42f7/src/webvowl/js/elements/properties/BaseProperty.js#L385).
