### ISSUE TITLE
Degree of Collapsing default

### ISSUE THREAD

**Issue by dolleyj** [VisualDataWeb/WebVOWL#18]
The default for the node collapsing filter seems to be the minimum of collapsing, 0 (zero). Is it possible to have the initial degree of node collapsing a different value than zero? 

Thank you!

**Comment by steffen-l** [comment]
Good point! We are currently discussing to preselect filters based on the size (and type) of ontology. We will also consider preselecting filters by adding variables to the URL of WebVOWL. This is not yet implemented but might come in the future. For the moment, the answer to your question is "no".

**Comment by dolleyj** [comment]
Thank you! I appreciate the prompt reply :)
