### ISSUE TITLE
Unable to download war release

### ISSUE THREAD

**Issue by dbeniamine** [VisualDataWeb/WebVOWL#180]
Hello,

I am trying to build a docker image for WebVOWL, but the [war download link](http://downloads.visualdataweb.de/webvowl_1.1.7.war) is not working (protocol error)

![image](https://user-images.githubusercontent.com/2989133/139822251-01c92a03-b16c-4bba-a5ba-e6c5f1394650.png)

So alternatively I am trying to build my own war file, but the instruction are unclear : I find how to build a war for OWL2VOWL but I do not know how to include WebVOWL inside it ...

**Comment by vitalis-wiens** [comment]
Hi, when you have build the war your have to inject webvowl into it.
the webvowl/deploy folder has to be then copied into the war file at the position
WEB-INF/classes/static

Alternatively, you can use the new docker image:
https://hub.docker.com/repository/docker/vitalisw/webvowl-117
