### ISSUE TITLE
WebVOWL is offline

### ISSUE THREAD

**Issue by Muffexx** [VisualDataWeb/WebVOWL#185]
Hello everyone.

Since several days the public WebVOWL at [https://service.tib.eu/webvowl/](https://service.tib.eu/webvowl/) is offline.
The "old" WebVOWL is still available at [http://vowl.visualdataweb.org/webvowl-old/webvowl-old.html](http://vowl.visualdataweb.org/webvowl-old/webvowl-old.html).

Any news on this?

Best Muffexx

**Comment by Muffexx** [comment]
Hello.
The service is still offline. :(
Best Muffexx

**Comment by vitalis-wiens** [comment]
Service has been restarted, it is back online :+1:

**Comment by Zack-83** [comment]
It is again offline... It seems that the project has been discontinued.

**Comment by Muffexx** [comment]
Hey @Zack-83

can't confirm. I can reach https://service.tib.eu/webvowl/ just fine. It seems to work properly.

regards

**Comment by Zack-83** [comment]
Thank you for pointing this. Then the link on the main page should be updated.

Are you or the TIB still taking care of the project?

![grafik](https://github.com/user-attachments/assets/a2c537d5-b090-42d7-a687-c57a729cba81)

**Comment by BlackDark** [comment]
Updated the link on the main page
