### ISSUE TITLE
Could not establish connection to OWL2VOWL service

### ISSUE THREAD

**Issue by jayh-aa** [VisualDataWeb/WebVOWL#190]
Hi all, am attempting to load up an ontology on the webservice at https://service.tib.eu/webvowl/ by uploading my own ttl file. Normally it works well and loads the ontology as expected, however today I get an error "Could not establish connection to OWL2VOWL service" and runs indefinitely.

**Comment by SOG-web** [comment]
please how did you fix this

**Comment by SOG-web** [comment]
this is the error i got

```
Retrieving ontology from file: idomal.owl
Could not establish connection to OWL2VOWL service
Trying to convert with other communication protocol.
```
