### ISSUE TITLE
Error Convertor.php not found

### ISSUE THREAD

**Issue by noorbakerally** [VisualDataWeb/WebVOWL#21]
I am getting this error, Converter.php was not found. Please make sure that PHP is running, can you please provide the file and state the location where it should be placed.

**Comment by linkvt** [comment]
Hi,
sorry for the long delay. We had to discuss how to handle this request.

A working `converter.php` file for connecting WebVOWL with OWL2VOWL can be found [HERE](https://gist.github.com/linkvt/2b0b47f1f7ad56ec15dd).
You should place it in the same directory as WebVOWL along with a jar file of [OWL2VOWL](https://github.com/VisualDataWeb/OWL2VOWL) with the name `owl2vowl.jar`.

Please consider that this is just an example; there are many different ways for communicating with OWL2VOWL. Although we use a `converter.php` similar to this example, we neither can give you support for any php related problems that may occur, nor guarantee that this works absolutely seamless.

Regards, Vincent
