### ISSUE TITLE
WebVOWL is awesome :)

### ISSUE THREAD

**Issue by baazoo** [VisualDataWeb/WebVOWL#23]
Sorry for opening an issue but I didn't know where to express my excitement. I looked at many network visualization projects. WebVOWL is by far the most sophisticated and comprehensive project I have seen so far. I can learn so much here.
Thank you for the great work :)

**Comment by steffen-l** [comment]
Thank you, baazoo, we appreciate your enthusiasm, and are glad to hear that WebVOWL is useful to you.
