### ISSUE TITLE
Pin Property

### ISSUE THREAD

**Issue by noorbakerally** [VisualDataWeb/WebVOWL#24]
Nice Software, but it would be great if we could pin property also in "pick & pin mode "

**Comment by blankdots** [comment]
it is already available see example:
![Uploading vowl_capture.gif…](VOWL pick and pin mode)

**Comment by BlackDark** [comment]
@blankdots he meant the pinning of properties.
We had it already integradeted some time ago and removed it due to incosistencies.
But than we changed the properties also to nodes in regards to the force layout.
We will reactivate this feature in the next time.

**Comment by blankdots** [comment]
@BlackDark oh, ok :)
