### ISSUE TITLE
Add support for DisjointUnion element

### ISSUE THREAD

**Issue by linkvt** [VisualDataWeb/WebVOWL#29]
### JSON (shortened)
```
{
    "type" : "owl:disjointUnionOf",
    "disjointUnion" : [ "class16", "class35" ]
}
```

### Visual Element
![disjointunion](https://cloud.githubusercontent.com/assets/3075401/13053899/31a6be56-d407-11e5-98f7-39cd37e725dc.png)

**Comment by BlackDark** [comment]
Sample output from OWL2VOWL:
 {
    "id" : "103",
    "type" : "owl:disjointUnion"
  }

{
    "iri" : "http://ontovibe.visualdataweb.org#LargeDisjointUnionClass",
    "baseIri" : "http://ontovibe.visualdataweb.org",
    "instances" : 0,
    "disjointUnion" : [ "15", "64", "5" ],
    "label" : {
      "IRI-based" : "LargeDisjointUnionClass"
    },
    "attributes" : [ "disjointUnion" ],
    "id" : "103"
  } ]
