### ISSUE TITLE
No hand cursor

### ISSUE THREAD

**Issue by steffen-l** [VisualDataWeb/WebVOWL#35]
No hand cursor for some of the menu items. The cursor changes to a hand only in some cases - missing CSS link?

**Comment by linkvt** [comment]
I'm not completely sure where the hand cursor is missing. Do you mean that there is no hand symbol above checkboxes?

Current master build for reference: [webvowl-master-cd2af24.zip](https://github.com/VisualDataWeb/WebVOWL/files/139597/webvowl-master-cd2af24.zip)

**Comment by steffen-l** [comment]
Cursor doesn't turn into hand icon on the items of the gravity, filter, and modes menus. It turns correctly for the ontology, export, and about menus. Bug appears in Firefox and Chrome.

**Comment by steffen-l** [comment]
I see. This is not wanted for check boxes and sliders. Didn't notice but makes sense. Sorry. Let's keep it this.
