### ISSUE TITLE
owl:complementOf and owl:disjointUnionOf

### ISSUE THREAD

**Issue by steffen-l** [VisualDataWeb/WebVOWL#45]
Those two concepts are not correctly visualized at the moment when generated with OntoBench.

**Comment by linkvt** [comment]
Incorrectly visualized disjointUnionOf fixed in a4968c0be63b694acda7bf7a0160254ebfe013b5.

`owl:complementOf` will be fixed in https://github.com/VisualDataWeb/OWL2VOWL/issues/15.
