### ISSUE TITLE
Add someValuesFrom and allValuesFrom

### ISSUE THREAD

**Issue by linkvt** [VisualDataWeb/WebVOWL#48]
Details here: https://github.com/VisualDataWeb/OWL2VOWL/issues/12#issuecomment-201580508

**Comment by steffen-l** [comment]
If someValuesFrom or allValuesFrom is defined together with a cardinality restriction, the cardinality restriction is simply added with a comma (e.g. "∃, 2..*" for someValuesFrom and minCardinality of 2).

**Comment by linkvt** [comment]
Merged in f2a877a2b1234b537425f93980dd431c7add8a95
