### ISSUE TITLE
missing step in readme

### ISSUE THREAD

**Issue by mael-morel** [VisualDataWeb/WebVOWL#5]
Hi guys, there's a missing step in the "simple" part of the readme :

```
bower install
```

Inspiring work by the way, thanks

**Comment by linkvt** [comment]
Hi,
`bower install` should also be executed when doing `npm install`. You can see this in the [package.json](/VisualDataWeb/WebVOWL/blob/master/package.json#L27). Didn't this work on your system?

And thanks for the compliment!

**Comment by linkvt** [comment]
worksforme
