### ISSUE TITLE
Opening local ontology directly from console

### ISSUE THREAD

**Issue by DrDizzle** [VisualDataWeb/WebVOWL#50]
Hello,
I'm using WebVOWL to visualize local ontologies. I have been pretty happy so far.
Now I want to improve workflow by directly opening my ontologies with one call.
Something like: firefox file:///.../webvowl/index.html#file=XYZ.json
What would be the easiest way to do this?

**Comment by linkvt** [comment]
Hi,

nice to hear that everything works well so far.

Since WebVOWL is usually run on a webserver, loading files from a local system would not be possible, because it would be a cross origin request which is usually blocked by the browser.

You can make it work for you if you modify a single line of code.
If you change [ontologyMenu.js#L89](https://github.com/VisualDataWeb/WebVOWL/blob/master/src/app/js/menu/ontologyMenu.js#L89), from this
`loadOntologyFromFile(filename);`
to this
`loadOntologyFromUri(filename, filename);`
This will break uploading local ontologies via the web interface. If that's a problem, there is another workaround.
You also can't use this with Chrome without adding another launching parameter, but it seemed that you're only using Firefox.

In my case I could open a local json with a url similar to this: `file:///C:/Users/.../WebVOWL/deploy/index.html#file=file:///C:/Users/.../WebVOWL/deploy/data/foaf.json`

**Comment by DrDizzle** [comment]
Hi,
Sorry for not writing sooner. I was working on something else.
I changed the code as shown and tried it. If I try to load any local files now, I'm getting these errors:

(browser console): NS_ERROR_DOM_BAD_URI: Access to restricted URI denied

(linux terminal): 1462200191024	addons.productaddons	WARN	Failed downloading XML, status: 0, reason: error

Any kind of help is appreciated.

**Comment by linkvt** [comment]
Can you comment the URL you used?

**Comment by DrDizzle** [comment]
firefox file:///var/tmp/WebVOWL-git/deploy/index.html#file=file:///home/os/Desktop/net2vowl/test/oEKb.141.json

This is the exact call I used, but the loading problem also occurres when I'm trying to load a file the regular way:
Ontology -> Select ontology file -> <Selecting file> -> Upload

**Comment by linkvt** [comment]
Hmm, did you adjust the code exactly as described above? As I mentioned there, this would break uploading ontologies from a local file.

You could test it with the attached version. I had to attach a gz file, because github seems to block zip files currently. I can open it eg. with 7zip.
[webvowl.gz](https://github.com/VisualDataWeb/WebVOWL/files/253438/webvowl.gz)


Uploading your ontology from a local file on the hosted WebVOWL does work, doesn't it? Because otherwise it might be a corrupt `json`.

**Comment by DrDizzle** [comment]
Yes, I did it exactly as you described it. The version you posted throws exactly the same error as my version.
When I upload my file to the hosted WebVOWL or build the newest version without changes, I can load the file the regular way, through the ontology menu. So the file seems to be valid.
I also found a different error. I don't know if I overlooked it or if it's new.

TypeError: S is undefined
u()                                          webvowl.js:2
t()                                           d3.min.js:1
oa.layout.force/l.tick()            d3.min.js:4
Rn()                                       d3.min.js:1
Tn()                                        d3.min.js:1

I would guess this is the main problem.

**Comment by linkvt** [comment]
Hmm thats strange. Could you attach the json file you used? 
I can't do that much just from your error description, since it's working for me. This would help a lot and let me debug the error you received.

**Comment by DrDizzle** [comment]
For some reason the upload isn't working. So, I've got to do it the old fashioned way:

`{
  "_comment" : "Created with OWL2VOWL (version 0.2.0), http://vowl.visualdataweb.org",
  "namespace" : [ ],
  "header" : {
    "languages" : [ "IRI-based", "undefined" ],
    "iri" : "file:/home/os/Desktop/net2vowl/tmp/oEKb.141.ttl"
  },
  "metrics" : {
    "classCount" : 20,
    "datatypeCount" : 0,
    "objectPropertyCount" : 19,
    "datatypePropertyCount" : 0,
    "propertyCount" : 19,
    "nodeCount" : 20,
    "axiomCount" : 197,
    "individualCount" : 0
  },
  "class" : [ {
    "id" : "class4",
    "type" : "externalclass"
  }, {
    "id" : "class16",
    "type" : "externalclass"
  }, {
    "id" : "class18",
    "type" : "externalclass"
  }, {
    "id" : "class7",
    "type" : "externalclass"
  }, {
    "id" : "class17",
    "type" : "externalclass"
  }, {
    "id" : "class13",
    "type" : "externalclass"
  }, {
    "id" : "class2",
    "type" : "externalclass"
  }, {
    "id" : "class3",
    "type" : "externalclass"
  }, {
    "id" : "class6",
    "type" : "externalclass"
  }, {
    "id" : "class8",
    "type" : "externalclass"
  }, {
    "id" : "class9",
    "type" : "externalclass"
  }, {
    "id" : "class10",
    "type" : "externalclass"
  }, {
    "id" : "class14",
    "type" : "externalclass"
  }, {
    "id" : "class12",
    "type" : "externalclass"
  }, {
    "id" : "class1",
    "type" : "externalclass"
  }, {
    "id" : "class11",
    "type" : "externalclass"
  }, {
    "id" : "class15",
    "type" : "externalclass"
  }, {
    "id" : "class5",
    "type" : "externalclass"
  }, {
    "id" : "class20",
    "type" : "externalclass"
  }, {
    "id" : "class19",
    "type" : "externalclass"
  } ],
  "classAttribute" : [ {
    "id" : "class4",
    "label" : {
      "IRI-based" : "zahlreich.1.1"
    },
    "iri" : "file:/share/os/zahlreich.1.1",
    "attributes" : [ "external" ],
    "annotations" : {
      "sort" : [ {
        "identifier" : "sort",
        "language" : "undefined",
        "value" : "nq",
        "type" : "label"
      } ],
      "entity" : [ {
        "identifier" : "entity",
        "language" : "undefined",
        "value" : "nonmeas-quality",
        "type" : "label"
      } ],
      "base" : [ {
        "identifier" : "base",
        "language" : "undefined",
        "value" : "zahlreich",
        "type" : "label"
      } ]
    },
    "instances" : 0
  }, {
    "id" : "class16",
    "label" : {
      "IRI-based" : "futter.1.1"
    },
    "iri" : "file:/share/os/futter.1.1",
    "attributes" : [ "external" ],
    "annotations" : {
      "gener" : [ {
        "identifier" : "gener",
        "language" : "undefined",
        "value" : "ge",
        "type" : "label"
      } ],
      "etype" : [ {
        "identifier" : "etype",
        "language" : "undefined",
        "value" : "1",
        "type" : "label"
      } ],
      "sort" : [ {
        "identifier" : "sort",
        "language" : "undefined",
        "value" : "s",
        "type" : "label"
      } ],
      "entity" : [ {
        "identifier" : "entity",
        "language" : "undefined",
        "value" : "prot-substance",
        "type" : "label"
      } ],
      "base" : [ {
        "identifier" : "base",
        "language" : "undefined",
        "value" : "Futter",
        "type" : "label"
      } ]
    },
    "instances" : 0
  }, {
    "id" : "class18",
    "label" : {
      "IRI-based" : "futtermittelindustrie.1.1"
    },
    "iri" : "file:/share/os/futtermittelindustrie.1.1",
    "attributes" : [ "external" ],
    "annotations" : {
      "gener" : [ {
        "identifier" : "gener",
        "language" : "undefined",
        "value" : "ge",
        "type" : "label"
      } ],
      "etype" : [ {
        "identifier" : "etype",
        "language" : "undefined",
        "value" : "1",
        "type" : "label"
      } ],
      "sort" : [ {
        "identifier" : "sort",
        "language" : "undefined",
        "value" : "io",
        "type" : "label"
      } ],
      "entity" : [ {
        "identifier" : "entity",
        "language" : "undefined",
        "value" : "institution",
        "type" : "label"
      } ],
      "base" : [ {
        "identifier" : "base",
        "language" : "undefined",
        "value" : "Futtermittelindustrie",
        "type" : "label"
      } ]
    },
    "instances" : 0
  }, {
    "id" : "class7",
    "label" : {
      "IRI-based" : "anbieten.1.4"
    },
    "iri" : "file:/share/os/anbieten.1.4",
    "attributes" : [ "external" ],
    "annotations" : {
      "gener" : [ {
        "identifier" : "gener",
        "language" : "undefined",
        "value" : "ge",
        "type" : "label"
      } ],
      "sort" : [ {
        "identifier" : "sort",
        "language" : "undefined",
        "value" : "da",
        "type" : "label"
      } ],
      "entity" : [ {
        "identifier" : "entity",
        "language" : "undefined",
        "value" : "nonment-action",
        "type" : "label"
      } ],
      "base" : [ {
        "identifier" : "base",
        "language" : "undefined",
        "value" : "anbieten",
        "type" : "label"
      } ]
    },
    "instances" : 0
  }, {
    "id" : "class17",
    "label" : {
      "IRI-based" : "c18"
    },
    "iri" : "file:/share/os/c18",
    "attributes" : [ "external" ],
    "annotations" : {
      "orth" : [ {
        "identifier" : "orth",
        "language" : "undefined",
        "value" : "angeboten",
        "type" : "label"
      } ],
      "gener" : [ {
        "identifier" : "gener",
        "language" : "undefined",
        "value" : "sp",
        "type" : "label"
      } ],
      "sort" : [ {
        "identifier" : "sort",
        "language" : "undefined",
        "value" : "da",
        "type" : "label"
      } ],
      "entity" : [ {
        "identifier" : "entity",
        "language" : "undefined",
        "value" : "nonment-action",
        "type" : "label"
      } ],
      "base" : [ {
        "identifier" : "base",
        "language" : "undefined",
        "value" : "anbieten",
        "type" : "label"
      } ]
    },
    "instances" : 0
  }, {
    "id" : "class13",
    "label" : {
      "IRI-based" : "c19"
    },
    "iri" : "file:/share/os/c19",
    "attributes" : [ "external" ],
    "annotations" : {
      "varia" : [ {
        "identifier" : "varia",
        "language" : "undefined",
        "value" : "con",
        "type" : "label"
      } ],
      "fact" : [ {
        "identifier" : "fact",
        "language" : "undefined",
        "value" : "real",
        "type" : "label"
      } ],
      "orth" : [ {
        "identifier" : "orth",
        "language" : "undefined",
        "value" : "",
        "type" : "label"
      } ],
      "etype" : [ {
        "identifier" : "etype",
        "language" : "undefined",
        "value" : "2",
        "type" : "label"
      } ],
      "sort" : [ {
        "identifier" : "sort",
        "language" : "undefined",
        "value" : "ab",
        "type" : "label"
      } ],
      "quant" : [ {
        "identifier" : "quant",
        "language" : "undefined",
        "value" : "nfquant",
        "type" : "label"
      } ],
      "entity" : [ {
        "identifier" : "entity",
        "language" : "undefined",
        "value" : "abs-object",
        "type" : "label"
      } ],
      "card" : [ {
        "identifier" : "card",
        "language" : "undefined",
        "value" : "2",
        "type" : "label"
      } ],
      "base" : [ {
        "identifier" : "base",
        "language" : "undefined",
        "value" : "Zusammensetzung",
        "type" : "label"
      } ]
    },
    "instances" : 0
  }, {
    "id" : "class2",
    "label" : {
      "IRI-based" : "mensch.1.1"
    },
    "iri" : "file:/share/os/mensch.1.1",
    "attributes" : [ "external" ],
    "annotations" : {
      "gener" : [ {
        "identifier" : "gener",
        "language" : "undefined",
        "value" : "ge",
        "type" : "label"
      } ],
      "etype" : [ {
        "identifier" : "etype",
        "language" : "undefined",
        "value" : "0",
        "type" : "label"
      } ],
      "sort" : [ {
        "identifier" : "sort",
        "language" : "undefined",
        "value" : "d",
        "type" : "label"
      } ],
      "entity" : [ {
        "identifier" : "entity",
        "language" : "undefined",
        "value" : "human-object",
        "type" : "label"
      } ],
      "base" : [ {
        "identifier" : "base",
        "language" : "undefined",
        "value" : "Mensch",
        "type" : "label"
      } ]
    },
    "instances" : 0
  }, {
    "id" : "class3",
    "label" : {
      "IRI-based" : "qualität.1.1"
    },
    "iri" : "file:/share/os/qualität.1.1",
    "attributes" : [ "external" ],
    "annotations" : {
      "gener" : [ {
        "identifier" : "gener",
        "language" : "undefined",
        "value" : "ge",
        "type" : "label"
      } ],
      "etype" : [ {
        "identifier" : "etype",
        "language" : "undefined",
        "value" : "0",
        "type" : "label"
      } ],
      "sort" : [ {
        "identifier" : "sort",
        "language" : "undefined",
        "value" : "io, oa",
        "type" : "label"
      } ],
      "entity" : [ {
        "identifier" : "entity",
        "language" : "undefined",
        "value" : "oper-attribute, prot-theor-concept",
        "type" : "label"
      } ],
      "base" : [ {
        "identifier" : "base",
        "language" : "undefined",
        "value" : "Qualität",
        "type" : "label"
      } ]
    },
    "instances" : 0
  }, {
    "id" : "class6",
    "label" : {
      "IRI-based" : "mittel.1.2"
    },
    "iri" : "file:/share/os/mittel.1.2",
    "attributes" : [ "external" ],
    "annotations" : {
      "gener" : [ {
        "identifier" : "gener",
        "language" : "undefined",
        "value" : "ge",
        "type" : "label"
      } ],
      "etype" : [ {
        "identifier" : "etype",
        "language" : "undefined",
        "value" : "0",
        "type" : "label"
      } ],
      "sort" : [ {
        "identifier" : "sort",
        "language" : "undefined",
        "value" : "io",
        "type" : "label"
      } ],
      "entity" : [ {
        "identifier" : "entity",
        "language" : "undefined",
        "value" : "prot-theor-concept",
        "type" : "label"
      } ],
      "base" : [ {
        "identifier" : "base",
        "language" : "undefined",
        "value" : "Mittel",
        "type" : "label"
      } ]
    },
    "instances" : 0
  }, {
    "id" : "class8",
    "label" : {
      "IRI-based" : "c11"
    },
    "iri" : "file:/share/os/c11",
    "attributes" : [ "external" ],
    "annotations" : {
      "orth" : [ {
        "identifier" : "orth",
        "language" : "undefined",
        "value" : "Mash",
        "type" : "label"
      } ],
      "varia" : [ {
        "identifier" : "varia",
        "language" : "undefined",
        "value" : "con",
        "type" : "label"
      } ],
      "fact" : [ {
        "identifier" : "fact",
        "language" : "undefined",
        "value" : "real",
        "type" : "label"
      } ],
      "refer" : [ {
        "identifier" : "refer",
        "language" : "undefined",
        "value" : "det",
        "type" : "label"
      } ],
      "gener" : [ {
        "identifier" : "gener",
        "language" : "undefined",
        "value" : "sp",
        "type" : "label"
      } ],
      "etype" : [ {
        "identifier" : "etype",
        "language" : "undefined",
        "value" : "0",
        "type" : "label"
      } ],
      "sort" : [ {
        "identifier" : "sort",
        "language" : "undefined",
        "value" : "d",
        "type" : "label"
      } ],
      "quant" : [ {
        "identifier" : "quant",
        "language" : "undefined",
        "value" : "one",
        "type" : "label"
      } ],
      "entity" : [ {
        "identifier" : "entity",
        "language" : "undefined",
        "value" : "human-object",
        "type" : "label"
      } ],
      "card" : [ {
        "identifier" : "card",
        "language" : "undefined",
        "value" : "1",
        "type" : "label"
      } ],
      "base" : [ {
        "identifier" : "base",
        "language" : "undefined",
        "value" : "Mash",
        "type" : "label"
      } ]
    },
    "instances" : 0
  }, {
    "id" : "class9",
    "label" : {
      "IRI-based" : "c12"
    },
    "iri" : "file:/share/os/c12",
    "attributes" : [ "external" ],
    "annotations" : {
      "gener" : [ {
        "identifier" : "gener",
        "language" : "undefined",
        "value" : "sp",
        "type" : "label"
      } ],
      "etype" : [ {
        "identifier" : "etype",
        "language" : "undefined",
        "value" : "0",
        "type" : "label"
      } ],
      "sort" : [ {
        "identifier" : "sort",
        "language" : "undefined",
        "value" : "na",
        "type" : "label"
      } ],
      "quant" : [ {
        "identifier" : "quant",
        "language" : "undefined",
        "value" : "one",
        "type" : "label"
      } ],
      "card" : [ {
        "identifier" : "card",
        "language" : "undefined",
        "value" : "1",
        "type" : "label"
      } ],
      "entity" : [ {
        "identifier" : "entity",
        "language" : "undefined",
        "value" : "nonoper-attribute",
        "type" : "label"
      } ],
      "base" : [ {
        "identifier" : "base",
        "language" : "undefined",
        "value" : "Nachname",
        "type" : "label"
      } ]
    },
    "instances" : 0
  }, {
    "id" : "class10",
    "label" : {
      "IRI-based" : "industrie.1.1"
    },
    "iri" : "file:/share/os/industrie.1.1",
    "attributes" : [ "external" ],
    "annotations" : {
      "gener" : [ {
        "identifier" : "gener",
        "language" : "undefined",
        "value" : "ge",
        "type" : "label"
      } ],
      "etype" : [ {
        "identifier" : "etype",
        "language" : "undefined",
        "value" : "1",
        "type" : "label"
      } ],
      "sort" : [ {
        "identifier" : "sort",
        "language" : "undefined",
        "value" : "io",
        "type" : "label"
      } ],
      "entity" : [ {
        "identifier" : "entity",
        "language" : "undefined",
        "value" : "institution",
        "type" : "label"
      } ],
      "base" : [ {
        "identifier" : "base",
        "language" : "undefined",
        "value" : "Industrie",
        "type" : "label"
      } ]
    },
    "instances" : 0
  }, {
    "id" : "class14",
    "label" : {
      "IRI-based" : "futtermittel.1.1"
    },
    "iri" : "file:/share/os/futtermittel.1.1",
    "attributes" : [ "external" ],
    "annotations" : {
      "gener" : [ {
        "identifier" : "gener",
        "language" : "undefined",
        "value" : "ge",
        "type" : "label"
      } ],
      "etype" : [ {
        "identifier" : "etype",
        "language" : "undefined",
        "value" : "0",
        "type" : "label"
      } ],
      "sort" : [ {
        "identifier" : "sort",
        "language" : "undefined",
        "value" : "io",
        "type" : "label"
      } ],
      "entity" : [ {
        "identifier" : "entity",
        "language" : "undefined",
        "value" : "prot-theor-concept",
        "type" : "label"
      } ],
      "base" : [ {
        "identifier" : "base",
        "language" : "undefined",
        "value" : "Futtermittel",
        "type" : "label"
      } ]
    },
    "instances" : 0
  }, {
    "id" : "class12",
    "label" : {
      "IRI-based" : "c14"
    },
    "iri" : "file:/share/os/c14",
    "attributes" : [ "external" ],
    "annotations" : {
      "orth" : [ {
        "identifier" : "orth",
        "language" : "undefined",
        "value" : "Futtermittelindustrie",
        "type" : "label"
      } ],
      "varia" : [ {
        "identifier" : "varia",
        "language" : "undefined",
        "value" : "con",
        "type" : "label"
      } ],
      "fact" : [ {
        "identifier" : "fact",
        "language" : "undefined",
        "value" : "real",
        "type" : "label"
      } ],
      "refer" : [ {
        "identifier" : "refer",
        "language" : "undefined",
        "value" : "det",
        "type" : "label"
      } ],
      "gener" : [ {
        "identifier" : "gener",
        "language" : "undefined",
        "value" : "sp",
        "type" : "label"
      } ],
      "etype" : [ {
        "identifier" : "etype",
        "language" : "undefined",
        "value" : "1",
        "type" : "label"
      } ],
      "sort" : [ {
        "identifier" : "sort",
        "language" : "undefined",
        "value" : "io",
        "type" : "label"
      } ],
      "quant" : [ {
        "identifier" : "quant",
        "language" : "undefined",
        "value" : "one",
        "type" : "label"
      } ],
      "entity" : [ {
        "identifier" : "entity",
        "language" : "undefined",
        "value" : "institution",
        "type" : "label"
      } ],
      "card" : [ {
        "identifier" : "card",
        "language" : "undefined",
        "value" : "1",
        "type" : "label"
      } ],
      "base" : [ {
        "identifier" : "base",
        "language" : "undefined",
        "value" : "Futtermittelindustrie",
        "type" : "label"
      } ]
    },
    "instances" : 0
  }, {
    "id" : "class1",
    "label" : {
      "IRI-based" : "nachname.1.1"
    },
    "iri" : "file:/share/os/nachname.1.1",
    "attributes" : [ "external" ],
    "annotations" : {
      "gener" : [ {
        "identifier" : "gener",
        "language" : "undefined",
        "value" : "ge",
        "type" : "label"
      } ],
      "etype" : [ {
        "identifier" : "etype",
        "language" : "undefined",
        "value" : "0",
        "type" : "label"
      } ],
      "sort" : [ {
        "identifier" : "sort",
        "language" : "undefined",
        "value" : "na",
        "type" : "label"
      } ],
      "entity" : [ {
        "identifier" : "entity",
        "language" : "undefined",
        "value" : "nonoper-attribute",
        "type" : "label"
      } ],
      "base" : [ {
        "identifier" : "base",
        "language" : "undefined",
        "value" : "Nachname",
        "type" : "label"
      } ]
    },
    "instances" : 0
  }, {
    "id" : "class11",
    "label" : {
      "IRI-based" : "c16"
    },
    "iri" : "file:/share/os/c16",
    "attributes" : [ "external" ],
    "annotations" : {
      "orth" : [ {
        "identifier" : "orth",
        "language" : "undefined",
        "value" : "Zusammensetzungen",
        "type" : "label"
      } ],
      "varia" : [ {
        "identifier" : "varia",
        "language" : "undefined",
        "value" : "con",
        "type" : "label"
      } ],
      "fact" : [ {
        "identifier" : "fact",
        "language" : "undefined",
        "value" : "real",
        "type" : "label"
      } ],
      "gener" : [ {
        "identifier" : "gener",
        "language" : "undefined",
        "value" : "ge",
        "type" : "label"
      } ],
      "etype" : [ {
        "identifier" : "etype",
        "language" : "undefined",
        "value" : "1",
        "type" : "label"
      } ],
      "sort" : [ {
        "identifier" : "sort",
        "language" : "undefined",
        "value" : "as",
        "type" : "label"
      } ],
      "quant" : [ {
        "identifier" : "quant",
        "language" : "undefined",
        "value" : "mult",
        "type" : "label"
      } ],
      "entity" : [ {
        "identifier" : "entity",
        "language" : "undefined",
        "value" : "nonment-stat-abs-situation",
        "type" : "label"
      } ],
      "base" : [ {
        "identifier" : "base",
        "language" : "undefined",
        "value" : "Zusammensetzung",
        "type" : "label"
      } ]
    },
    "instances" : 0
  }, {
    "id" : "class15",
    "label" : {
      "IRI-based" : "c17"
    },
    "iri" : "file:/share/os/c17",
    "attributes" : [ "external" ],
    "annotations" : {
      "orth" : [ {
        "identifier" : "orth",
        "language" : "undefined",
        "value" : "Qualitäten",
        "type" : "label"
      } ],
      "varia" : [ {
        "identifier" : "varia",
        "language" : "undefined",
        "value" : "con",
        "type" : "label"
      } ],
      "fact" : [ {
        "identifier" : "fact",
        "language" : "undefined",
        "value" : "real",
        "type" : "label"
      } ],
      "gener" : [ {
        "identifier" : "gener",
        "language" : "undefined",
        "value" : "ge",
        "type" : "label"
      } ],
      "etype" : [ {
        "identifier" : "etype",
        "language" : "undefined",
        "value" : "1",
        "type" : "label"
      } ],
      "sort" : [ {
        "identifier" : "sort",
        "language" : "undefined",
        "value" : "io, oa",
        "type" : "label"
      } ],
      "quant" : [ {
        "identifier" : "quant",
        "language" : "undefined",
        "value" : "mult",
        "type" : "label"
      } ],
      "entity" : [ {
        "identifier" : "entity",
        "language" : "undefined",
        "value" : "oper-attribute, prot-theor-concept",
        "type" : "label"
      } ],
      "base" : [ {
        "identifier" : "base",
        "language" : "undefined",
        "value" : "Qualität",
        "type" : "label"
      } ]
    },
    "instances" : 0
  }, {
    "id" : "class5",
    "label" : {
      "IRI-based" : "present.0"
    },
    "iri" : "file:/share/os/present.0",
    "attributes" : [ "external" ],
    "annotations" : {
      "etype" : [ {
        "identifier" : "etype",
        "language" : "undefined",
        "value" : "0",
        "type" : "label"
      } ],
      "sort" : [ {
        "identifier" : "sort",
        "language" : "undefined",
        "value" : "t",
        "type" : "label"
      } ],
      "entity" : [ {
        "identifier" : "entity",
        "language" : "undefined",
        "value" : "tem-sit-descriptor",
        "type" : "label"
      } ],
      "base" : [ {
        "identifier" : "base",
        "language" : "undefined",
        "value" : "present",
        "type" : "label"
      } ]
    },
    "instances" : 0
  }, {
    "id" : "class20",
    "label" : {
      "IRI-based" : "mash.0"
    },
    "iri" : "file:/share/os/mash.0",
    "attributes" : [ "external" ],
    "annotations" : {
      "sort" : [ {
        "identifier" : "sort",
        "language" : "undefined",
        "value" : "fe",
        "type" : "label"
      } ],
      "entity" : [ {
        "identifier" : "entity",
        "language" : "undefined",
        "value" : "for-entity",
        "type" : "label"
      } ],
      "base" : [ {
        "identifier" : "base",
        "language" : "undefined",
        "value" : "Mash",
        "type" : "label"
      } ]
    },
    "instances" : 0
  }, {
    "id" : "class19",
    "label" : {
      "IRI-based" : "zusammensetzung.1.1"
    },
    "iri" : "file:/share/os/zusammensetzung.1.1",
    "attributes" : [ "external" ],
    "annotations" : {
      "gener" : [ {
        "identifier" : "gener",
        "language" : "undefined",
        "value" : "ge",
        "type" : "label"
      } ],
      "etype" : [ {
        "identifier" : "etype",
        "language" : "undefined",
        "value" : "0",
        "type" : "label"
      } ],
      "sort" : [ {
        "identifier" : "sort",
        "language" : "undefined",
        "value" : "as",
        "type" : "label"
      } ],
      "entity" : [ {
        "identifier" : "entity",
        "language" : "undefined",
        "value" : "nonment-stat-abs-situation",
        "type" : "label"
      } ],
      "base" : [ {
        "identifier" : "base",
        "language" : "undefined",
        "value" : "Zusammensetzung",
        "type" : "label"
      } ]
    },
    "instances" : 0
  } ],
  "property" : [ {
    "id" : "property5",
    "type" : "owl:objectProperty"
  }, {
    "id" : "property19",
    "type" : "owl:objectProperty"
  }, {
    "id" : "property6",
    "type" : "owl:objectProperty"
  }, {
    "id" : "property13",
    "type" : "owl:objectProperty"
  }, {
    "id" : "property1",
    "type" : "owl:objectProperty"
  }, {
    "id" : "property2",
    "type" : "owl:objectProperty"
  }, {
    "id" : "property9",
    "type" : "owl:objectProperty"
  }, {
    "id" : "property3",
    "type" : "owl:objectProperty"
  }, {
    "id" : "property4",
    "type" : "owl:objectProperty"
  }, {
    "id" : "property14",
    "type" : "owl:objectProperty"
  }, {
    "id" : "property17",
    "type" : "owl:objectProperty"
  }, {
    "id" : "property7",
    "type" : "owl:objectProperty"
  }, {
    "id" : "property8",
    "type" : "owl:objectProperty"
  }, {
    "id" : "property10",
    "type" : "owl:objectProperty"
  }, {
    "id" : "property16",
    "type" : "owl:objectProperty"
  }, {
    "id" : "property11",
    "type" : "owl:objectProperty"
  }, {
    "id" : "property12",
    "type" : "owl:objectProperty"
  }, {
    "id" : "property18",
    "type" : "owl:objectProperty"
  }, {
    "id" : "property15",
    "type" : "owl:objectProperty"
  } ],
  "propertyAttribute" : [ {
    "id" : "property5",
    "label" : {
      "IRI-based" : "1",
      "undefined" : "sub"
    },
    "iri" : "file:/share/os/1",
    "attributes" : [ "external" ],
    "domain" : "class8",
    "range" : "class2"
  }, {
    "id" : "property19",
    "label" : {
      "IRI-based" : "0",
      "undefined" : "attr"
    },
    "iri" : "file:/share/os/0",
    "attributes" : [ "external" ],
    "domain" : "class8",
    "range" : "class9"
  }, {
    "id" : "property6",
    "label" : {
      "IRI-based" : "10",
      "undefined" : "temp"
    },
    "iri" : "file:/share/os/10",
    "attributes" : [ "external" ],
    "domain" : "class17",
    "range" : "class5"
  }, {
    "id" : "property13",
    "label" : {
      "IRI-based" : "5",
      "undefined" : "preds"
    },
    "iri" : "file:/share/os/5",
    "attributes" : [ "external" ],
    "domain" : "class11",
    "range" : "class19"
  }, {
    "id" : "property1",
    "label" : {
      "IRI-based" : "4",
      "undefined" : "sub"
    },
    "iri" : "file:/share/os/4",
    "attributes" : [ "external" ],
    "domain" : "class12",
    "range" : "class18"
  }, {
    "id" : "property2",
    "label" : {
      "IRI-based" : "3",
      "undefined" : "sub"
    },
    "iri" : "file:/share/os/3",
    "attributes" : [ "external" ],
    "domain" : "class9",
    "range" : "class1"
  }, {
    "id" : "property9",
    "label" : {
      "IRI-based" : "12",
      "undefined" : "*itms.1"
    },
    "iri" : "file:/share/os/12",
    "attributes" : [ "external" ],
    "domain" : "class13",
    "range" : "class11"
  }, {
    "id" : "property3",
    "label" : {
      "IRI-based" : "2",
      "undefined" : "val"
    },
    "iri" : "file:/share/os/2",
    "attributes" : [ "external" ],
    "domain" : "class9",
    "range" : "class20"
  }, {
    "id" : "property4",
    "label" : {
      "IRI-based" : "11",
      "undefined" : "scar"
    },
    "iri" : "file:/share/os/11",
    "attributes" : [ "external" ],
    "domain" : "class13",
    "range" : "class12"
  }, {
    "id" : "property14",
    "label" : {
      "IRI-based" : "14",
      "undefined" : "prop"
    },
    "iri" : "file:/share/os/14",
    "attributes" : [ "external" ],
    "domain" : "class13",
    "range" : "class4"
  }, {
    "id" : "property17",
    "label" : {
      "IRI-based" : "9",
      "undefined" : "agt"
    },
    "iri" : "file:/share/os/9",
    "attributes" : [ "external" ],
    "domain" : "class17",
    "range" : "class12"
  }, {
    "id" : "property7",
    "label" : {
      "IRI-based" : "8",
      "undefined" : "ornt"
    },
    "iri" : "file:/share/os/8",
    "attributes" : [ "external" ],
    "domain" : "class17",
    "range" : "class8"
  }, {
    "id" : "property8",
    "label" : {
      "IRI-based" : "13",
      "undefined" : "*itms.2"
    },
    "iri" : "file:/share/os/13",
    "attributes" : [ "external" ],
    "domain" : "class13",
    "range" : "class15"
  }, {
    "id" : "property10",
    "label" : {
      "IRI-based" : "7",
      "undefined" : "subs"
    },
    "iri" : "file:/share/os/7",
    "attributes" : [ "external" ],
    "domain" : "class17",
    "range" : "class7"
  }, {
    "id" : "property16",
    "label" : {
      "IRI-based" : "16",
      "undefined" : "sub"
    },
    "iri" : "file:/share/os/16",
    "attributes" : [ "external" ],
    "domain" : "class14",
    "range" : "class6"
  }, {
    "id" : "property11",
    "label" : {
      "IRI-based" : "6",
      "undefined" : "pred"
    },
    "iri" : "file:/share/os/6",
    "attributes" : [ "external" ],
    "domain" : "class15",
    "range" : "class3"
  }, {
    "id" : "property12",
    "label" : {
      "IRI-based" : "15",
      "undefined" : "assoc"
    },
    "iri" : "file:/share/os/15",
    "attributes" : [ "external" ],
    "domain" : "class14",
    "range" : "class16"
  }, {
    "id" : "property18",
    "label" : {
      "IRI-based" : "18",
      "undefined" : "sub"
    },
    "iri" : "file:/share/os/18",
    "attributes" : [ "external" ],
    "domain" : "class18",
    "range" : "class10"
  }, {
    "id" : "property15",
    "label" : {
      "IRI-based" : "17",
      "undefined" : "assoc"
    },
    "iri" : "file:/share/os/17",
    "attributes" : [ "external" ],
    "domain" : "class18",
    "range" : "class14"
  } ]
}`

**Comment by linkvt** [comment]
I just found out, that the file has to be in the same directory or a subdirectory of the folder where the `index.html` is placed, or otherwise the browser will block the request, see more here: [Same-origin_policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy)
You might have to configure your browser to allow these requests, I guess there are some ressources on the internet.

I just visualized your json with and exported the SVG file: [exported-graph.zip](https://github.com/VisualDataWeb/WebVOWL/files/266596/exported-graph.zip)
I noticed you're using an old version of OWL2VOWL (but the latest available I think) - there will soon be a new release for OWL2VOWL with many improvements.

**Comment by DrDizzle** [comment]
It's finally working. Thank you.
Just using a subdirectory was the best solution for me. I'm not very familiar with CORS and it doesn't really matter where I store my data.
