### ISSUE TITLE
is there any way to see the instances?

### ISSUE THREAD

**Issue by AniaDavid** [VisualDataWeb/WebVOWL#54]
I tried your application it is so cool, but i just could see my classes (after uploading my OWL ontology), is there anyway please so  I can also see my instances ? (and ofc the relationships between them)

Looking forward to hearing from you

Regards

**Comment by steffen-l** [comment]
Thank you! VOWL visualizes the TBox of ontologies but only little ABox information for several reasons. Accordingly, you can see classes and their relationships in WebVOWL. You also get some info about datatypes and the number of individuals that are instances of the classes. However, the actual individuals and relationships between them are not visualized in VOWL 2. If you have a look at the specifications of VOWL 1 and VOWL 2 at http://purl.org/vowl/spec/v2/ and http://purl.org/vowl/spec/v1/ you might get a better idea about the pros and cons of this design decision.
