### ISSUE TITLE
Cannot prepoulate WebVOWL with own ontologies

### ISSUE THREAD

**Issue by hammar** [VisualDataWeb/WebVOWL#55]
Hi guys,

I've been trying to use the standard WebVOWL distribution (downloaded from http://vowl.visualdataweb.org/webvowl.html) with my own custom JSON files (generated from source ontologies by manually invoking owl2vowl), but am having no luck - I'm just getting the following error:

webvowl.app.js:formatted:841Uncaught Error: Cannot find module './ONTOLOGYNAME.json'.

I'm by no means a JS expert, but it appears that somewhere in the release process you end up with the default "demo" ontologies being hardcoded as modules into the webvowl.app.js  file (see attached screenshot). Is this the intended behavior? If so, how would you recommend I go about visualising a pre-processed JSON file added manually to the data directory? Would I need to rebuild WebVOWL from source for every new such file being added?

The reasons for me attempting to do this is:

1) I want users to simply be able to select their ontology from the "Ontology" menu (which I will adapt to include the project ontologies) and not have to upload files by hand every time. Modifying just the the menu in the index.html file when a new ontology is added is a lot less work than rebuilding the whole WebVOWL project.

2) The ontologies in question are under NDA, so they cannot be published on a public IRI. Instead I'm intending to let the users run WebVOWL with a local basic http server (the built in SimpleHTTPServer in Python 2)

/Karl

![webvowl](https://cloud.githubusercontent.com/assets/68027/15703110/fa8854da-27e3-11e6-89b1-6fbebaf963a9.png)

**Comment by linkvt** [comment]
Hi Karl,

I could replicate the issue with your provided informations and tested the fix successfully.
I changed *abusing* the webpack file loader for copying the resources by copying them with an extra plugin as you can see in b64582d95dcabd47e486e1efdcc89978264a854e.

I build the current version which should be released soon: [webvowl-master-c7fbc82.zip](https://github.com/VisualDataWeb/WebVOWL/files/301493/webvowl-master-c7fbc82.zip)

Regards, Vincent

**Comment by hammar** [comment]
Hi,

I tested the build you linked and can confirm that it works as expected. Many thanks for your work, this will greatly simplify our workflow!

/Karl
