### ISSUE TITLE
Label for named owl:unionOf 

### ISSUE THREAD

**Issue by jmatsushita** [VisualDataWeb/WebVOWL#58]
Here's an example with SPDX 2.0 http://vowl.visualdataweb.org/webvowl/index.html#iri=http://spdx.org/rdf/terms/spdx-2-0-ontology.owl.xml

![image](https://cloud.githubusercontent.com/assets/356097/17004194/ebd9cb0a-4ea1-11e6-9b77-9104a16b2d15.png)

The central element is the SPDX `Package` class and it seems that the fact that it's named should Maybe the Union visual should be a small icon below the Title in the way that `(external)` is displayed below external classes?

PS: Amazing that this is now Open Source! It's great!

**Comment by steffen-l** [comment]
Thansk for sharing this change request (and sorry for the late reaction). We integrated that change in the latest version of WebVOWL some time ago (which is, however, not yet available at http://vowl.visualdataweb.org/webvowl.html). Will come soon...

**Comment by steffen-l** [comment]
Here is the link to the release candidate (that has some known bugs), in case you want to try the updated notation and WebVOWL version: http://visualdataweb.de/webvowl/
