### ISSUE TITLE
[feature request] Filter by property

### ISSUE THREAD

**Issue by jmatsushita** [VisualDataWeb/WebVOWL#59]
I'd be in particular quite fond of being able to hide items with a `term_status: deprecated`.

**Comment by linkvt** [comment]
AFAIK there are currently no plans to implement this feature, but you could try it yourself by copying and modifying an existing filter like [setOperatorFilter.js](https://github.com/VisualDataWeb/WebVOWL/blob/master/src/webvowl/js/modules/setOperatorFilter.js).
After creating such a filter you would need to export it in [entry.js#L28](https://github.com/VisualDataWeb/WebVOWL/blob/master/src/webvowl/js/entry.js#L28) of webvowl to be able to use it in the app.
