### ISSUE TITLE
Color classes and subclasses differently

### ISSUE THREAD

**Issue by jmavasa** [VisualDataWeb/WebVOWL#62]
Hi

What would I need to change to be able to color classes and subclasses with a different color. Is there a way to show individuals on the visualization. Thank you

**Comment by steffen-l** [comment]
Currently, external classes (i.e., classes from a different namespace) are colored differently (in an inverted way). The color of a certain type of class can be easily changed in the source code in a similar way. However, any class can be a subclass of another class and a subclass can also have subclasses itself. Identifying these cases might need a bit more of programming logic, but shouldn't be too difficult (using some hierachization).

WebVOWL focuses on the visualization of classes and their relationships and datatypes. Individuals are only indicated by circle size and listed in the sidebar. Integrating individuals in the visualization would be possible (they are listed in the generated JSON file), but could easily clutter the graph. However, you can try to change the code of WebVOWL accordingly.
