### ISSUE TITLE
Web.app.js

### ISSUE THREAD

**Issue by hemanth23** [VisualDataWeb/WebVOWL#63]
Hi Team,

How to get the full version of Web.app.js, i have minified version of web.app.js that too i have pulled from the following link. http://vowl.visualdataweb.org/webvowl/js/webvowl.app.js

How to get the full version of web.app.js.

**Comment by blankdots** [comment]
The full version of web.app.js is a sum of files - I think it is constructed from the files in this repository: https://github.com/VisualDataWeb/WebVOWL/tree/c79c4bfe59f076dca9ecb481928190e20854fb02/src/app/js
