### ISSUE TITLE
CertificateException: No subject alternative DNS matching ...

### ISSUE THREAD

**Issue by carueda** [VisualDataWeb/WebVOWL#66]
(Perhaps this will better belong to https://github.com/VisualDataWeb/OWL2VOWL, but the issue is exposed in WebVOWL at http://vowl.visualdataweb.org/webvowl/index.html, so capturing it here.)

When trying to visualize http://vowl.visualdataweb.org/webvowl/index.html#iri=https://xdomes.org/ont/xdomes/testvoc

WebVOWL fails to load it showing:

```
Conversion failed. Error log: 
org.semanticweb.owlapi.io.OWLOntologyCreationIOException
java.security.cert.CertificateException: No subject alternative DNS name matching xdomes.org found.
```

![vowl ssl certificate error with xdomes url](https://cloud.githubusercontent.com/assets/556505/19838145/4d538194-9e86-11e6-9b05-2bff440de0b0.png)

But https://xdomes.org/ont/xdomes/testvoc does actually exist and resolves to an ontology representation (unless requested from a typical browser). 

Validation with the W3C validator service:

https://www.w3.org/RDF/Validator/rdfval?URI=https%3A%2F%2Fxdomes.org%2Font%2Fxdomes%2Ftestvoc&PARSE=Parse+URI%3A+&TRIPLES_AND_GRAPH=PRINT_TRIPLES&FORMAT=PNG_EMBED

![2016-10-30_1011](https://cloud.githubusercontent.com/assets/556505/19838300/6790659c-9e89-11e6-8d8c-a47b978bd0de.png)

confirms that there's no problem with the HTTPS access.

Interestingly, https://www.w3.org/ns/ssn (just as different example with HTTPS access on a different domain) works fine: http://vowl.visualdataweb.org/webvowl/index.html#iri=https://www.w3.org/ns/ssn

Perhaps there's some issue with the version of the underlying OWL API library (or its configuration)?

**Comment by steffen-l** [comment]
Works in the new (latest) WebVOWL version (that will hopefully be released soon): http://visualdataweb.de/webvowl/#iri=https://xdomes.org/ont/xdomes/testvoc
