### ISSUE TITLE
Can't load UniProt core onlology

### ISSUE THREAD

**Issue by laughedelic** [VisualDataWeb/WebVOWL#67]
I'm trying to get a visualization of the UniProt core ontology: 
http://vowl.visualdataweb.org/webvowl/#iri=http://purl.uniprot.org/core/
But I get 

> Conversion failed. Error log: java.lang.NullPointerException null

This message is not very informative. Could you help me to figure out what is the problem?
It suggests me to validate the ontology. I did it and the validator didn't show any problems.

**Comment by steffen-l** [comment]
If you try with the latest version of WebVOWL, it works fine. Here's the link to the release candidate (which still has some known bugs): http://visualdataweb.de/webvowl/#iri=http://purl.uniprot.org/core/

Hope this helps.

**Comment by laughedelic** [comment]
This helps, thanks! So the problem was in WebVOWL, not in the ontology. Are you going to release 1.0.0 anytime soon?

**Comment by steffen-l** [comment]
Yes, that's at least planned ;-) Happy to hear the new version solved your problem.
