### ISSUE TITLE
Remove unconnected literals

### ISSUE THREAD

**Issue by steffen-l** [VisualDataWeb/WebVOWL#73]
Literal nodes should never appear alone in the VOWL graph, but must always be connected via a datatype property. Since there can be literal nodes without connections in the JSON file (due to a peculiarity of the OWL API), we mighte better remove all unconnected literal nodes from the graph before it is drawn.

The artifact of unconnected literal nodes can be observed e.g. in the visualization of the FOAF graph:
http://visualdataweb.de/webvowl/#iri=http://xmlns.com/foaf/0.1/

**Comment by linkvt** [comment]
In my opinion this is rather an OWL2VOWL issue since OWL2VOWL generates the VOWL-JSON and WebVOWL just visualizes it.
It could however be quickly implemented with a filter that is always enabled and not shown in the GUI.

**Comment by steffen-l** [comment]
You are right. OWL2VOWL should ensure that the generated output is correct. Let's better don't start such a "dirty hacking" in WebVOWL ;-)
