### ISSUE TITLE
Ontology is not showing relationships when the count is more than 100

### ISSUE THREAD

**Issue by vikashait** [VisualDataWeb/WebVOWL#78]
We have classes which have ingoing outgoing counts more than 100 and for those cases, webvowl doesnt render them at all. is there way to show them?

**Comment by steffen-l** [comment]
Could you provide an example?

**Comment by vikashait** [comment]
Ok, I need to build one example for you as I cannot share data from my project. This problem can be reproduced easily by having a class having objectProperty more than 100 ,(it could be ingoing or outgoing)

**Comment by vitalis-wiens** [comment]
I`m not able to reproduce this behavior.
I tried ingoing and outgoing properties with a count of 150 properties / nodes 

see the attached zip file for the 2 examples (ingoing/outgoing)
[example.zip](https://github.com/VisualDataWeb/WebVOWL/files/675667/example.zip)

Is it possible that the filter "Degree of collapsing" is greater than 0 or maybe an other filter is active? 

Could you provide an example if you still have this behavior?

**Comment by emilie1862** [comment]
I've been testing out WebVOWL by giving it data from LOV. If a vocabulary is provided where the combined classes and properties are very large >~2,000, the conversion to VOWL takes significant time. Sometimes it even causes the page to crash. But if it does return, only ~100 nodes are displayed.

Here is one example: http://lov.okfn.org/dataset/lov/vocabs/dicom
This vocabulary contains about 8,000 terms

http://visualdataweb.de/webvowl/#iri=http://lov.okfn.org/dataset/lov/vocabs/dicom/versions/2015-01-11.n3

**Comment by vitalis-wiens** [comment]
On initialization webVOWL sets up a degree filter(Degree of collapsing).
That`s why the "Filter"-button is highlighted in yellow. 
In your example it is automatically set to be > 60. 

Go to "Filter" and set the slider of the "Degree of collapsing" slider to 0.
Then it will show you all the relationships.

**Comment by emilie1862** [comment]
Thanks for your response. Setting the slider of the "Degree of collapsing" slider to 0 showed all of relationships. 

Using Chrome 55.0.2883.95 that Ontology took 18 minutes to load. Then when I changed the "Degree of collapsing" slider, the view took 8 minutes to update and navigation has extreme lag. Are there any plans to implement an asynchronous response, or make similar improvements to increase performance?

**Comment by steffen-l** [comment]
Thanks for your feedback, Emilie! Yes, there are plans to improve the performance and scalability of WebVOWL. However, the visualization of large ontologies is challenging in several regards. Don't expect something soon (it is a mayor issue - not only in WebVOWL), but we will work on it and plan to make some updates to WebVOWL this year that improve its performance and scalability. These works might take a while and will certainly not solve all issues, but will hopefully be of help in a number of use cases.
