### ISSUE TITLE
Cannot upload local ontology

### ISSUE THREAD

**Issue by iulitaro** [VisualDataWeb/WebVOWL#8]
Ontology is trying to run a file convertor.php and the error message is "Server responded with a status of 405 (Method not allowed)"

But I could not find any PHP file in the current .git repository...

![capture](https://cloud.githubusercontent.com/assets/940531/9289929/5cce60de-437f-11e5-82e7-38fec523f862.PNG)

i.

**Comment by linkvt** [comment]
Hi,
as you already noticed, we didn't include the php file. This is intended, because it doesn't really belong to WebVOWL. We should put this info into the README file.

The php file doesn't do really much: It checks whether the passed IRI seems to be OK, passes it then to an executable jar of [OWL2VOWL](https://github.com/VisualDataWeb/OWL2VOWL) and returns the output.

We will fix the issues and a few more bugs we collected soon.

**Comment by iulitaro** [comment]
Hi @linkvt 

thanks for your answer, really appreciate it. 

That makes sense, so in order to have the .json files in the VOWL format ( like this https://github.com/VisualDataWeb/WebVOWL/blob/master/src/js/data/foaf.json ) , the Java OWL2VOWL convertor is used. 

Is there by any chance any restriction of the input file to feed into the convertor - I see OWL files are accepted but could I also upload OWL in RDF/XML format, for example?

Would there be any way to do this using NodeJS ? (I am currently developing an academic project and would require the metrics that are in the VOWL file).

Thanks again and thumbs up on the effort invested in this project. :+1:

**Comment by iulitaro** [comment]
Allright I found a way to call the .jar file from nodeJS, by following this suggestion.

http://stackoverflow.com/questions/12892195/how-to-run-a-jar-file-with-node-js-child-process-api

Thanks,
i.

**Comment by steffen-l** [comment]
Thanks for your interest in WebVOWL. Hope it will run fine on your nodeJS instance (usually, it should). Regarding the input formats, you can feed the converter with a couple of formats. Basically, any format that is valid OWL and can be read by the OWL API should work: http://owlapi.sourceforge.net/

**Comment by iulitaro** [comment]
Thank you @steffen-l and @linkvt for the support.  I have successfully integrated the Java convertor into the NodeJS app. With it I was able to deserialize an ontology into a JSON file of type VOWL. Would it be possible to do the serialization of a VOWL JSON file into an ontology too? (Need to reconstruct an ontology after "partitioning it" for example to remove certain nodes and so on)

**Comment by steffen-l** [comment]
I'm glad to hear that you managed to integrate VOWL into your NodeJS app. Currently, the converter works only in one direction (i.e., from OWL to VOWL), but doesn't support a conversion the other way round. For that reason, it currently only supports the case of ontology visualization but not the case of visual ontology editing, which would require to convert the edited VOWL visualization back into OWL. I'm sorry to tell you.

**Comment by iulitaro** [comment]
Understood, @steffen-l . Not sure also that there exist such tools that do this kind of transformation (for example to transform an ontology from JSON to OWL). By the way, is VOWL based on OWL API or is it an independent effort? I would like to know in order to see if I can use any of the functions from OWL API.

Regards,
Iulia

**Comment by steffen-l** [comment]
There might be such tools for RDF/JSON or JSON-LD. Please note that the VOWL-JSON schema is not a proper OWL serialization, i.e., it has been designed to enable an efficient generation of the VOWL graph visualization and is not intended to be a representation of OWL itself.

Regarding your second question: Yes, the VOWL converter is based on the OWL API, so you may use those functions if you add them in the code - see https://github.com/VisualDataWeb/OWL2VOWL

**Comment by iulitaro** [comment]
Allright, understood, thanks for the fast reply @steffen-l . :+1:
