### ISSUE TITLE
Node Location Persistence

### ISSUE THREAD

**Issue by NickyBobby** [VisualDataWeb/WebVOWL#81]
Hey everyone,

I was wondering if anyone could help me with node location persistence. My client would like to be able to refresh the page and have the nodes load back up to the same spot where they were at before reload. I am currently setting the node locations to local storage every time they move - with the node ID as the key and the x,y coordinates as the value. It should only be one line of code to implement this feature.

All I need to know is where the x,y coordinates are initially being set upon page reload, then check to see if the values exist in local storage, if they exist then set them to the node before being rendered. I suspect that the x,y coords get set somewhere in either parser.js or options.js.

If anyone is able to help me with this issue, that would be greatly appreciated.

Hope you are all having a great day!

-Nick

**Comment by NickyBobby** [comment]
```hey```

**Comment by NickyBobby** [comment]
So I was able to persist node locations by setting their x and y coordinates to localStorage whenever they move. With this code inside of the function `recalculatePositions`:

```	function recalculatePositions() {
		// Set node positions
		nodeElements.attr("transform", function (node) {
			// sets current node location to location storage to persist user sessions
			var id = this.id;
			localStorage.setItem(id, JSON.stringify({x: node.x, y: node.y}))

			return "translate(" + node.x + "," + node.y + ")";
		});
```

And then I just added a simple check to see if that node has been set in localStorage before we render the nodes upon load up. With this code inside of the function `setForceLayoutData`:

```	function setForceLayoutData(classNodes, labelNodes, links) {
		var coords;
		var d3Links = [];
		links.forEach(function (link) {
			d3Links = d3Links.concat(link.linkParts());
		});
		for (var i = 0; i<classNodes.length; i++) {
			if (localStorage.getItem(classNodes[i].id())) {
				coords = JSON.parse(localStorage.getItem(classNodes[i].id()))
				classNodes[i].x = coords.x
				classNodes[i].y = coords.y
				classNodes[i].locked(true)
			}
		}
```

Since this isn't a real "issue", I'm gonna close it but here's the code if anyone wants to persist node locations from different user sessions. Hope this will be helpful for other people

**Comment by steffen-l** [comment]
Thanks for sharing your solution, Nicholas. Please note that the latest version of WebVOWL implements a similar feature when saving the node positions and user settings in the exported JSON. You can try that at: http://visualdataweb.de/webvowl/
