### ISSUE TITLE
centering screen on searched element

### ISSUE THREAD

**Issue by leshek-pawlak** [VisualDataWeb/WebVOWL#84]
Hi,
I'm using this great library for a while, and I'm wondering about an improvement the search feature.

After the click on the dropdown menu, the searched node is highlighted. 
What do you think about centering the screen on it? 

I already wrote some code to focus on searched element on my fork.
If you're interested in I can do a pull request.

Cheers,
Leszek

**Comment by steffen-l** [comment]
Thanks, Leshek. We already implemented that feature in an experimental version and will integrate it in the next WebVOWL release. It come with a nice and smooth focus animation. Might be a similar implementation as your solution.

**Comment by leshek-pawlak** [comment]
That's great news! 
So, I'm waiting for new release.

Thanks.

**Comment by vitalis-wiens** [comment]
The new feature is now available on gitHub.

Click on the "target" button next to the search entry form (right side) to center the viewport around 
the searched node (On multiple found entries you can press the "target" button several times, which circles between the found entries in the graph )


In the next days we will also release it on the web server.

Additionally dynamic halo radii are added.
