### ISSUE TITLE
editing ABox

### ISSUE THREAD

**Issue by ChipNowacek** [VisualDataWeb/WebVOWL#86]
I need to be able to visualize _and_ edit. More specifically, I need to visualize and edit the ABox. Suggestions?

**Comment by vitalis-wiens** [comment]
WebVOWL in its current state allows you only to visualize given data. 
Editing is not supported. 
If you need to visualize your data ASAP you can try to export your data as a json file, and then 
modify it to your needs and then visualize the new json file
