### ISSUE TITLE
owl:keys

### ISSUE THREAD

**Issue by mgskjaeveland** [VisualDataWeb/WebVOWL#88]
Add support for owl:keys: https://www.w3.org/TR/2012/REC-owl2-syntax-20121211/#Keys

**Comment by steffen-l** [comment]
Keys are supported by the latest WebVOWL version - see e.g. http://visualdataweb.de/webvowl/#iri=http://visualdataweb.de/ontobench/ontology/ontology.ttl?features=haskey

Or do you mean something else? Could you clarify?

**Comment by mgskjaeveland** [comment]
Sorry, my bad. 

BTW, I notice in the example to give, that it is not possible to see that there the key is composite.

**Comment by steffen-l** [comment]
Not sure if I got you right, but it is right that VOWL and WebVOWL don't support complex datatypes for now.

**Comment by mgskjaeveland** [comment]
Sorry, I was not very clear. What I meant is that there seems to be no difference in the visualisation of these two cases:

1. one key with two properties:
`:HasKeyClass rdf:type owl:Class ;
	     owl:hasKey ( :hasKeyProperty_2 :hasKeyProperty_1 ) .`
2. two keys with one property each:
`:HasKeyClass rdf:type owl:Class ;
	     owl:hasKey ( :hasKeyProperty_2 ) , ( :hasKeyProperty_1 ) .`
