### ISSUE TITLE
"No classes found!" when ontologies are in named graphs

### ISSUE THREAD

**Issue by jmvanel** [VisualDataWeb/WebVOWL#91]
Aparently WebVOWL expects ontologies to be in the default (unnamed) graph of the SPARQL database.
When ontologies are in named graphs,
WebVOWL says:
"No classes found!"

For instance, try this SPARQL : 
http://vowl.visualdataweb.org/ldvowl/#/graph?endpointURL=http:%2F%2Fsemantic-forms.cc:9111%2Fsparql

NOTE:
semantic_forms is both a SPARQL endpoint, and a LOD framework, where all RDF documents are in their own URI , see the doc. : 
https://github.com/jmvanel/semantic_forms/wiki/User_manual#the-rdf-cache-and-database

**Comment by steffen-l** [comment]
This issue relates to LD-VOWL, not to WebVOWL. Could you add it to the right repository please: https://github.com/VisualDataWeb/LD-VOWL

Cheers.

**Comment by jmvanel** [comment]
DONE paste the issue , sorry .

**Comment by steffen-l** [comment]
no problem ;-) thanks for reporting it.
