### ISSUE TITLE
Update in WebVOWL

### ISSUE THREAD

**Issue by iyerramkumar** [VisualDataWeb/WebVOWL#94]
Hi ,

Sorry for second query. We want an update process in WebVOWL for the ontology. Is it on the cards? Please let us know. We plan to use SPARQL Update (using Apache JENA) to add such capability otherwise.

Thanks
Ram

**Comment by steffen-l** [comment]
Ontology editing is not supported in WebVOWL. You have to edit the ontology elsewhere and reload it into WebVOWL (i.e. update it in WebVOWL). Note that WebVOWL is a pure "ontology visualizer" for now, not an "ontology editor". Using SPARQL Update is not on our list, so please go ahead integrating it yourself.

**Comment by iyerramkumar** [comment]
Thanks Steffen. We will integrate it ourselves. Thanks for the great work.

**Comment by white-gecko** [comment]
Hey Steffen, since you have now the WebVOWL Editor. Is the WebVOWL Editor capable of connecting to a SPARQL Endpoint and sending SPARQL Update requests?

**Comment by steffen-l** [comment]
No, WebVOWL (incl. WebVOWL Editor) is not running on SPARQL (yet) - it works only file-based (for now). Other projects linked at http://vowl.visualdataweb.org make use of SPARQL, such as LD-VOWL and QueryVOWL, and most notably VoCol. Note that VoCol integrates some SPARQL-based visualization and text-based editing with the integrated Turtle Editor, but no visual editing (yet).

**Comment by white-gecko** [comment]
Thank you for the clarification.
