### ISSUE TITLE
Support for Microsoft Edge (with a little help)?

### ISSUE THREAD

**Issue by dannmartens** [VisualDataWeb/WebVOWL#96]
It would appear Microsoft Edge can be coerced to render the page properly, if the User-Agent string is set to Chrome or Firefox. 
![Screenshot](https://pbs.twimg.com/media/DCDxIf3XUAIpkyP.jpg:large)

WebVOWL is a really nice tool, so I investigated IE11/Edge support (again), as I am facing customers who can only use IE11. Pretty much given up on that; see also your closed ['Rendering Issue in IE11' #79](https://github.com/VisualDataWeb/WebVOWL/issues/79) - but there appears some hope left for Edge.

Is there anything in the client-side code which would explain this behavior?

**Comment by vitalis-wiens** [comment]
We will investigate the support of Edge for the next release, which should be available soon, 
but I still recommend to use Firefox or Chrome.

**Comment by dannmartens** [comment]
No argument with the recommendation :)

And anyway, the working application on Edge demonstrates a much poorer performance, once it is loaded.

However, the object of me trying this, is to make WebVOWL work for a range of customers who cannot choose the browser they'd like to use, but would like to use the application we're building.

**Comment by steffen-l** [comment]
We totally understand your point! However, once we developed WebVOWL, there were some crucial issues with D3 + SVG + Graph-Visualization + Internet Explorer that made using WebVOWL in IE impossible. The situation might have changed with Microsoft Edge so that we will reconsider this issue when working towards the next release, as stated by Vitalis. Just give us a couple of days... ;-)

**Comment by dannmartens** [comment]
Thanks! It would appear IE11 seems to benefit from that update, as well. Although I wouldn't be surprised that this applies to a certain combination of OS and patch levels, only. On a Windows 10 machine with both Edge and Internet Explorer 11 installed, the rendering has improved dramatically and both browsers show similar results, with IE11 producing a higher update rate.

**Comment by dannmartens** [comment]
Seeing is believing :)
![Screenshot1](https://pbs.twimg.com/media/DCW6ffNXgAEoC6x.jpg:large)
![Screenshot2](https://pbs.twimg.com/media/DCW6ffLXkAENawF.jpg:large)

**Comment by steffen-l** [comment]
The latest version of WebVOWL we just released still shows the warning but allows to use MS IE and Edge at least (in case it works with these browsers, which is not guaranteed though).
