### ISSUE TITLE
Project Download Errors

### ISSUE THREAD

**Issue by njolee** [VisualDataWeb/WebVOWL#99]
Hi, 

I'm new here. I'm interested it customizing WebVowl. I understand WebVowl can be downloaded from two sources, visualdataweb.org and Github.

*Downloading the project from visualdataweb.org at http://downloads.visualdataweb.de/webvowl_1.0.4.zip

The application runs fine (just as it does on the web). I simply click on the index.html file and everything opens up and works. But I can’t work with this package because the source files are minified and appear obfuscated. 

So I turn to GitHub.

*Downloading the project from Github. 

When I download the project from Github, there’s a totally different directory structure. And a number of files cannot be found (see errrors below). I also see “raw” HTML as if it’s not finding CSS files.

Loading failed for the <script> with source “file:///Users/jlee101255/Desktop/WebVowl/WebVOWL-master/src/js/d3.min.js”.  index.html:204

Loading failed for the <script> with source “file:///Users/jlee101255/Desktop/WebVowl/WebVOWL-master/src/js/webvowl.js”.  index.html:205

Loading failed for the <script> with source “file:///Users/jlee101255/Desktop/WebVowl/WebVOWL-master/src/js/webvowl.app.js”.  index.html:206

ReferenceError: webvowl is not defined[Learn More]  index.html:207:1

When I copy these files to the sub-directories where they are expected to be, I get an error saying that the application can’t load the ontologies. 

Is there something I’m missing with the GitHub download. Why doesn’t it work properly like the download from visualdataweb.org?

Thanks in advance for your help!

Jay

**Comment by vitalis-wiens** [comment]
Hi, you have to build the source code,
Description is given in the readme.md
In the section "simple"

When you build the source then you get a deploy folder which has the
index.html
(Same structure as the downloaded zip file)

Have fun :)
Vitalis

Am 30.08.2017 9:35 nachm. schrieb "njolee" <notifications@github.com>:

**Comment by njolee** [comment]
Hi Vitalis,

Thanks so much! I see a few comments in some of the files that aren't
minified, but do you know if there is any document of the code, for
example, what js file is responsible for displaying the text inside the
nodes.

This paper appears on the documentation page, but it is more theoretical.
http://www.semantic-web-journal.net/content/visualizing-ontologies-vowl-0

Thanks again!

Jay

**Comment by steffen-l** [comment]
Hi Jay, I am afraid, there is no technical documentation of WebVOWL apart from the comments in the code and the scientific papers (which discuss VOWL on a conceptual level). However, the code structure is well-organized - getting an overview and implementing minor changes and adaptations shouldn't be too difficult even without a technical documentation.
